{
 "title": "AmazonEKS Split Cost Dashboard",
 "description": "AmazonEKS Split Cost Dashboard",
 "time": { "from": "now-7d", "to": "now-720m" },
 "templating": {
  "list": [
   { "name": "CURDatasource", "query": "grafana-athena-datasource" },
   { "name": "CWDatasource", "query": "cloudwatch" },
   {
    "name": "CurTable",
    "label": "CUR Table",
    "query": {}
   },
   {
    "name": "LinkedAccounts",
    "label": "Linked Accounts",
    "query": {}
   },
   {
    "name": "Regions",
    "label": "Regions",
    "query": {}
   },
   {
    "name": "Services",
    "label": "Services",
    "query": {}
   },
   { "name": "CURGranularity", "label": "CUR Granularity", "query": "month,week,day,hour" },
   { "name": "CWGranularity", "label": "CW Granularity", "query": "2628000,604800,86400,3600,300" },
   {
    "name": "ChargeType",
    "label": "Charge Type",
    "query": {}
   },
   {
    "name": "CostCategoryName",
    "label": "Cost Category Name",
    "query": {}
   },
   { "name": "InstanceId", "label": "Instance Id" },
   {
    "name": "EKSCluster",
    "label": "EKS Cluster",
    "query": {}
   },
   {
    "name": "EKSNamespace",
    "label": "EKS Cluster Namespace",
    "query": {}
   },
   {
    "name": "EKSPodName",
    "label": "EKS Cluster Pod Name",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style='font-size: 20px'>\n<span>AmazonEKS Split Cost Dashboard</span>\n</h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dashboard Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": " ",
     "type": "text",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "options": {
      "content": "### AmazonEKS Split Cost Allocation Dashboard\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Proin facilisis \nsapien eget sagittis elementum. Vivamus lectus dolor, elementum scelerisque sapien ut, \ntristique aliquet mauris. Ut sapien sapien, consectetur vitae nunc at, porttitor \npharetra massa. Cras posuere viverra nisi quis laoreet. Pellentesque habitant \nmorbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque et turpis nisi. \nFusce non quam id ipsum tincidunt fermentum. Aenean justo purus, convallis non condimentum vel, \nsagittis ut nunc. Phasellus vulputate urna quis libero convallis, vel euismod sapien suscipit. \nSuspendisse euismod sapien non venenatis egestas. Vivamus mollis sed urna ac lacinia. Aenean et lobortis libero, sed sodales leo. Integer justo elit, tristique in fringilla sit amet, finibus a nisl. Donec non ante ut magna venenatis mollis. Suspendisse ipsum tortor, fermentum et arcu non, suscipit porta ligula. "
     },
     "targets": [
      {}
     ]
    }
   ]
  },
  { "title": "AmazonEKS Namespace Metrics ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU per Namespace over Cost ",
   "type": "timeseries",
   "description": "Aggregated CPU utilization per namespace and the cost per cluster for timeperiod",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "accountId": "all",
     "expression": "SEARCH('{ContainerInsights,ClusterName,Namespace} MetricName=\"pod_cpu_utilization\"', 'Average', $CWGranularity)",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Average"
    },
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT\ndate_trunc('$CURGranularity', line_item_usage_start_date) as date,\nSUM(split_line_item_split_cost + split_line_item_unused_cost) as Cost\nFROM\n$CurTable\nWHERE\n$__timeFilter(line_item_usage_start_date) \nAND line_item_operation LIKE 'EKSPod-EC2' \nAND line_item_usage_type LIKE '%EKS-EC2-vCPU-Hours'\nAND SPLIT_PART(line_item_resource_id, ':', 4) = '$Regions'\nAND resource_tags['aws_eks_cluster_name'] = '$EKSCluster'\nGROUP BY\n1\n"
    }
   ]
  },
  {
   "title": "Memory per Namespace over Cost ",
   "type": "timeseries",
   "description": "Aggregated memory utilization per namespace and the cost per cluster for timeperiod",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "accountId": "all",
     "expression": "SEARCH('{ContainerInsights,ClusterName,Namespace} MetricName=\"pod_memory_utilization\"', 'Average', $CWGranularity)",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Average"
    },
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT\ndate_trunc('$CURGranularity', line_item_usage_start_date) as date,\nSUM(split_line_item_split_cost + split_line_item_unused_cost) as Cost\nFROM\n$CurTable\nWHERE\n$__timeFilter(line_item_usage_start_date) \nAND line_item_operation LIKE 'EKSPod-EC2' \nAND line_item_usage_type LIKE '%EKS-EC2-GB-Hours'\nAND SPLIT_PART(line_item_resource_id, ':', 4) = '$Regions'\nAND resource_tags['aws_eks_cluster_name'] = '$EKSCluster'\nGROUP BY\n1\n"
    }
   ]
  },
  {
   "title": "Total Cluster Split Cost",
   "type": "timeseries",
   "description": "Aggregated memory utilization per namespace and the cost per cluster for timeperiod",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT\ndate_trunc('$CURGranularity', line_item_usage_start_date) as date,\nSUM(split_line_item_public_on_demand_unused_cost) + SUM(split_line_item_public_on_demand_split_cost) as Cost\nFROM\n$CurTable\nWHERE\n$__timeFilter(line_item_usage_start_date) \nAND line_item_operation LIKE 'EKSPod-EC2' \nAND (line_item_usage_type LIKE '%EKS-EC2-GB-Hours' OR line_item_usage_type LIKE '%EKS-EC2-vCPU-Hours')\nAND SPLIT_PART(line_item_resource_id, ':', 4) = '$Regions'\nAND resource_tags['aws_eks_cluster_name'] = '$EKSCluster'\nGROUP BY\n1\n"
    }
   ]
  },
  {
   "title": "Instance Types Observed in Time Period",
   "type": "bargauge",
   "description": "Instance types observed in the $timefilter",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \n    product_instance_type,\n    COUNT(*) as instance_type_count\nFROM (\n    SELECT DISTINCT \n        line_item_resource_id, \n        product_instance_type,\n        line_item_usage_type \n    FROM $CurTable \n    WHERE line_item_resource_id in (\n        SELECT DISTINCT(split_line_item_parent_resource_id) \n        FROM $CurTable\n        WHERE \n        $__timeFilter(line_item_usage_start_date) \n        AND line_item_operation LIKE 'EKSPod-EC2' \n        AND line_item_usage_type LIKE '%EKS-EC2-vCPU-Hours' \n        AND SPLIT_PART(line_item_resource_id, ':', 4) = '$Regions'\n        AND resource_tags['aws_eks_cluster_name'] = '$EKSCluster'\n        AND split_line_item_parent_resource_id LIKE '%i-%'\n    ) \n    AND line_item_usage_type LIKE '%Box%'\n) as subquery\nGROUP BY product_instance_type\nORDER BY instance_type_count DESC;\n"
    }
   ]
  },
  {
   "title": "Cost Per Namespace",
   "type": "bargauge",
   "description": "Cost per Namespace in timeperiod (memory and compute)",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \nSPLIT_PART(line_item_resource_id, '/', 3) as namespace,\nSUM(split_line_item_split_cost) as cost\nFROM \n$CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_product_code IN ('AmazonEKS')\n  AND line_item_line_item_type  IN ('DiscountedUsage', 'Usage', 'SavingsPlanCoveredUsage','SavingsPlanRecurringFee','SavingsPlanNegation','SavingsPlanUpfrontFee')\n  AND split_line_item_split_cost > 0\n  AND SPLIT_PART(line_item_resource_id, ':', 4) = '$Regions'\n  AND resource_tags['aws_eks_cluster_name'] = '$EKSCluster'\nGROUP BY \n1"
    }
   ]
  },
  {
   "title": "Unused Cost Per Namespace",
   "type": "bargauge",
   "description": "Unused Cost per Namespace in timeperiod (memory and compute)",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \nSPLIT_PART(line_item_resource_id, '/', 3) as namespace,\nSUM(split_line_item_unused_cost) as cost\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_product_code IN ('AmazonEKS')\n  AND line_item_line_item_type  IN ('DiscountedUsage', 'Usage', 'SavingsPlanCoveredUsage','SavingsPlanRecurringFee','SavingsPlanNegation','SavingsPlanUpfrontFee')\n  AND split_line_item_unused_cost > 0\n  AND SPLIT_PART(line_item_resource_id, ':', 4) = '$Regions'\n  AND resource_tags['aws_eks_cluster_name'] = '$EKSCluster'\nGROUP BY \n1"
    }
   ]
  },
  {
   "title": "Total Split Cost / Unused Cost",
   "type": "stat",
   "description": "Total Cost per Namespace in timeperiod (memory and compute)",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \nSUM(split_line_item_unused_cost) + SUM(split_line_item_split_cost) as cost\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_product_code IN ('AmazonEKS', 'AmazonEC2')\n  AND line_item_line_item_type  IN ('DiscountedUsage', 'Usage', 'SavingsPlanCoveredUsage','SavingsPlanRecurringFee','SavingsPlanNegation','SavingsPlanUpfrontFee')\n  AND SPLIT_PART(line_item_resource_id, ':', 4) = '$Regions'\n  AND resource_tags['aws_eks_cluster_name'] = '$EKSCluster'\n"
    }
   ]
  },
  {
   "title": "AmazonEKS Service Cost",
   "type": "stat",
   "description": "Cost for EKS Cluster",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \nSUM(line_item_unblended_cost) as cost\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_product_code = 'AmazonEKS'\n  AND line_item_usage_type LIKE '%AmazonEKS-Hours:perCluster'\n  AND product_region_code = '$Regions'\n  AND SPLIT_PART(line_item_resource_id, '/', 2) =  '$EKSCluster'\n"
    }
   ]
  },
  {
   "title": "Cluster Data Transfer Cost - $EKSCluster",
   "type": "stat",
   "description": "AmazonEKS Data Transfer Cost",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT\nSUM(CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN savings_plan_savings_plan_effective_cost\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN reservation_effective_cost\n    WHEN line_item_line_item_type = 'Usage' THEN line_item_unblended_cost\n    ELSE 0 \n  END) AS Cost\nFROM\n$CurTable\nWHERE\n$__timeFilter(line_item_usage_start_date) \nAND line_item_usage_type like '%DataTransfer%'\nAND product_from_region_code = '$Regions'\nAND resource_tags['aws_eks_cluster_name'] = '$EKSCluster';"
    }
   ]
  },
  {
   "title": "Network Tx Bytes",
   "type": "timeseries",
   "description": "The number of bytes per second being transmitted over the network by the pod.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "accountId": "all",
     "expression": "SEARCH('{ContainerInsights,ClusterName,Namespace} MetricName=\"pod_network_tx_bytes\"', 'Average', $CWGranularity)",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Average"
    },
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT\ndate_trunc('$CURGranularity', line_item_usage_start_date) as date,\nSUM(line_item_unblended_cost) as Cost\nFROM\n$CurTable\nWHERE\n$__timeFilter(line_item_usage_start_date) \nAND line_item_usage_type like '%DataTransfer%'\nAND product_from_region_code = '$Regions'\nAND resource_tags['aws_eks_cluster_name'] = '$EKSCluster'\nGROUP BY\n1\n"
    }
   ]
  },
  { "title": "Top 500 Instances by Cost", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "EKS Cluster 500 Instances by Cost",
   "type": "table",
   "description": "Instances observed in the $EKSCluster for period: ",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \n  line_item_resource_id as Instance,\n  product_instance_type,\n  CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN 'Savings Plan'\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN 'Reserved Instance'\n    WHEN line_item_line_item_type = 'Usage' THEN 'On Demand'\n    ELSE 'On Demand'\n  END AS \"Purchase Type\",\n  SUM(CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN savings_plan_savings_plan_effective_cost\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN reservation_effective_cost\n    WHEN line_item_line_item_type = 'Usage' THEN line_item_unblended_cost\n    ELSE 0 \n  END) AS \"Amortized Cost\",\n  SUM(line_item_unblended_cost) as \"Unblended Cost\"\nFROM \n  $CurTable\nWHERE\n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_usage_account_id IN ('$LinkedAccounts')\n  AND product_region_code in ('$Regions')\n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_resource_id LIKE 'i-%'\n  AND line_item_usage_type LIKE ('%Box%')\n  AND product['vcpu'] <> ''\n  AND resource_tags['user_eks_cluster_name'] = '$EKSCluster'\nGROUP BY\n1,2,3\nORDER BY \n\"Amortized Cost\" DESC\nLIMIT 500;\n"
    }
   ]
  },
  {
   "title": "EKS Instance Explorer: $InstanceId",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 }
  },
  {
   "title": " Section Overview",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 56 },
   "options": {
    "content": "<font size=\"2\">\nThis section displays the average compute, disk and network metrics for the current specified instance ${InstanceId}.  The visuals are impacted by selections made from the inpute parameters and the time period.\n\n\n###### Parameters\nCUR Granulairty: ${CURGranularity}     CloudWatch Granulairty: ${CWGranularity}   \n</font>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Instance Compute Cost",
   "type": "stat",
   "description": "Total Instance cost for $instanceId for period: ${__from:date:iso} - ${__to:date:iso}",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \n  SUM(CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN savings_plan_savings_plan_effective_cost\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN reservation_effective_cost\n    WHEN line_item_line_item_type = 'Usage' THEN line_item_unblended_cost\n    ELSE 0 \n  END) AS \"Total Instance Amortized Cost\"\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_resource_id = '$InstanceId'\n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_line_item_type NOT IN ('Tax')\nORDER BY \n  \"Total Instance Amortized Cost\" DESC;"
    }
   ]
  },
  {
   "title": "Last Seen in CUR",
   "type": "stat",
   "description": "This visual displays the date the instance was lass seen in the CUR.  The CUR is searched for the past 12 months.\n\nKeep in mind the CUR update times happen up to three times daily, so you may see this metric lag behind depending on when the update last happened.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \n  DATE_FORMAT(line_item_usage_start_date, '%M %d, %Y ') as \"Last Seen Timestamp\"\nFROM \n  $CurTable\nWHERE \n  line_item_usage_start_date >= date_add('month', -12, current_date)\n  AND line_item_resource_id = '$InstanceId'\n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type LIKE '%Box%'\n  AND line_item_line_item_type NOT IN ('Tax') \nORDER BY \"Last Seen Timestamp\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "EC2: CPU Utilization Vs Cost (${CURGranularity})",
   "type": "timeseries",
   "description": "The first visual displays the instance cost per $CURGranularity from the cost and usage report.  The second visual reports the instance average CPU per ${CWGranularity}(s) for the given time period: ${__from:date:iso} - ${__to:date:iso}",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \n  date_trunc('$CURGranularity', line_item_usage_start_date) as date,\n  SUM(CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN savings_plan_savings_plan_effective_cost\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN reservation_effective_cost\n    WHEN line_item_line_item_type = 'Usage' THEN line_item_unblended_cost\n    ELSE 0 \n  END) AS \"Total Instance Amortized Cost\"\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_resource_id = '$InstanceId'\n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type LIKE ('%Box%')\n  AND line_item_line_item_type NOT IN ('Tax')\nGROUP BY\n1\nORDER BY \n  \"Total Instance Amortized Cost\" DESC;"
    },
    {
     "accountId": "all",
     "dimensions": { "InstanceId": "$InstanceId" },
     "expression": "SEARCH('{AWS/EC2,InstanceId} MetricName=\\\"CPUUtilization\\\" $InstanceId ', 'Average', 300)",
     "metricEditorMode": 1,
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "period": "$CWGranularity",
     "queryMode": "Metrics",
     "region": "$Regions",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "sqlExpression": "{\n    \"view\": \"timeSeries\",\n    \"stacked\": false,\n    \"region\": \"us-east-1\",\n    \"metrics\": [\n        [ \"AWS/Usage\", \"CallCount\", \"Type\", \"API\", \"Resource\", \"RunInstances\", \"Service\", \"EC2\", \"Class\", \"None\" ]\n    ]\n}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "public rate per hour",
   "type": "stat",
   "description": "Instance type and instance public rate as pulled from the cost and usage report.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \n  line_item_unblended_rate as \"public_rate\",\n  product_instance_type\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_resource_id = '$InstanceId'\n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type LIKE ('%Box%')\n  AND line_item_line_item_type NOT IN ('Tax')\nORDER BY \n  line_item_usage_start_date DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Purchase Type",
   "type": "stat",
   "description": "Purchase type observed for $instanceId for period: ${__from:date:iso} - ${__to:date:iso}",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \n  DISTINCT\n  CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN 'Savings Plan'\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN 'Reserved Instance'\n    WHEN line_item_line_item_type = 'Usage' THEN 'On Demand'\n    ELSE 'Other'\n  END\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_resource_id = '$InstanceId'\n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type LIKE '%Box%'\n  AND line_item_line_item_type NOT IN ('Tax') "
    }
   ]
  },
  {
   "title": "Instance Average CPU Utilization",
   "type": "stat",
   "description": "Average Instance CPU for $instanceId for period: ${__from:date:iso} - ${__to:date:iso}.  \n\nThis field will highlight red if the instance average CPU is < 5% in the given time period.  This indicates the instance may be a candidate for rightsizing based on CPU only.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "InstanceId": "$InstanceId" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "period": "$CWGranularity",
     "queryMode": "Metrics",
     "region": "$Regions",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "$InstanceId: NetworkOut Traffic",
   "type": "timeseries",
   "description": "This visual displays data transfer out cost data at a granularity of ${CURGranularity} and CloudWatch Network Out traffic at a CloudWatch granularity of ${CWGranularity}(s) for $InstanceId  during time period: ${__from:date:iso} - ${__to:date:iso}.  \n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expression": "SUM(REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} $InstanceId MetricName=\"NetworkOut\"', 'Sum', $CWGranularity )))/$CWGranularity",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "$Regions",
     "statistic": "Average"
    },
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \n  date_trunc('$CURGranularity', line_item_usage_start_date) as date,\n  SUM(line_item_unblended_cost) as datatransfer_cost\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_resource_id = '$InstanceId'\n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type LIKE ('%Bytes')\n  AND line_item_line_item_type NOT IN ('Tax')\nGROUP BY\n1"
    }
   ]
  },
  {
   "title": "$InstanceId: NetworkIn Traffic",
   "type": "timeseries",
   "description": "This visual displays the Network in traffic for $InstanceId at a CloudWatch granularity of ${CWGranularity}(s) during time period: ${__from:date:iso} - ${__to:date:iso}.  \n\nThere is no charge for incoming network thus we do not display cost and usage data from CUR for NetworkIn",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expression": "SUM(REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} $InstanceId MetricName=\"NetworkIn\"', 'Sum', $CWGranularity )))/$CWGranularity",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "$Regions",
     "statistic": "Average"
    }
   ]
  }
 ]
}