{
 "title": "COAST - EC2 Compute",
 "description": "EC2 Compute Dashboard",
 "time": { "from": "now-30d", "to": "now-720m" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "grafana-athena-datasource" },
   {
    "name": "CurTable",
    "label": "CUR Table",
    "query": {}
   },
   {
    "name": "LinkedAccounts",
    "label": "Linked Accounts",
    "query": {}
   },
   {
    "name": "Regions",
    "label": "Regions",
    "query": {}
   },
   {
    "name": "Services",
    "label": "Services",
    "query": {}
   },
   { "name": "CURGranularity", "label": "CUR Granularity", "query": "month,week,day,hour" },
   { "name": "CWGranularity", "label": "CW Granularity", "query": "2628000,604800,86400,3600" },
   {
    "name": "ChargeType",
    "label": "Charge Type",
    "query": {}
   },
   {
    "name": "TagKey",
    "label": "Tag Key",
    "query": {}
   },
   {
    "name": "TagValue",
    "label": "Tag Value",
    "query": {}
   },
   {
    "name": "CostCategoryName",
    "label": "Cost Category Name",
    "query": {}
   },
   {
    "name": "CostCategoryValue",
    "label": "Cost Category Value",
    "query": {}
   },
   {
    "name": "PanelTop25SpendPercentage",
    "query": {}
   },
   {
    "name": "TotalAccountInOrganization",
    "query": {}
   },
   { "name": "InstanceId", "label": "Instance Id" }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style='font-size: 20px'>\n<span style='color: #AF69EE;font-weight: bold'>C</span>ost <span style='color: #AF69EE;font-weight: bold'>O</span>ptimization <span style='color: #AF69EE;font-weight: bold'>A</span>nd <span style='color: #AF69EE;font-weight: bold'>S</span>avings <span style='color: #AF69EE;font-weight: bold'>T</span>ool (<span style='color: #AF69EE;font-weight: bold'>COAST</span>) <br> <span style=\"font-size: 18px\"> for Amazon Managed Grafana - EC2 Dashboard</span>\n</h1>"
   },
   "targets": [
    {}
   ]
  },
  { "title": "How to use this dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "options": {
    "content": "### EC2 Compute Dashboard\n\nThe EC2 Dashboard offers visualizations that display aggregated EC2 compute usage across your infrastructure. Additionally, it provides visuals that showcase cost, usage, and performance metrics for individual EC2 instances specified in the parameter text box.\n\nTo effectively utilize this dashboard, you must fulfill the following prerequisites:\n\n- Set up a Cost and Usage Report (CUR) 2.0, either at the payer account level or within your individual AWS account.\n- Create a data source for the CUR 2.0 data. This can be accomplished using our data export CloudFormation template.\n  - If you create the CUR 2.0 datasource manually, it needs to be named 'COAST-CUR20-2024-07-15'\n- If you plan to use this dashboard in your payer account and have access to the payer's CUR 2.0, you will need to configure CloudWatch cross-account replication for the accounts you wish to monitor.\n\nBy meeting these requirements, you can leverage the EC2 Dashboard to gain insights into your EC2 compute usage, costs, and performance metrics, enabling you to optimize your resources and make informed decisions."
   },
   "targets": [
    {}
   ]
  },
  { "title": "EC2: Aggregated Compute View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
   "options": {
    "content": "<font size=\"2\">\nThis section displays the average aggregated compute metrics for all EC2 Instances in account ${LinkedAccounts} within ${Regions}.  The visuals are impacted by selections made from the inpute parameters and the time period.\n\n\n###### Parameters\nCUR Granulairty: ${CURGranularity}     CloudWatch Granulairty: ${CWGranularity}   \n</font>\n"
   }
  },
  {
   "type": "stat",
   "description": "This visual displays the cost for all EC2 Running Instances from the Cost and Usage Report (CUR) for the current selected time period: ${__from:date:iso} - ${__to:date:iso}",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \n  SUM(line_item_unblended_cost)\nFROM $CurTable\nWHERE\n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_usage_account_id IN ('$LinkedAccounts')\n  AND product_region_code in ('$Regions')\n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type LIKE ('%Box%')\n  AND line_item_resource_id LIKE 'i-%'"
    }
   ]
  },
  {
   "type": "stat",
   "description": "This visual displays the average VCPU count/hour as observed from the Cost and Usage Report (CUR) for the current selected time period: ${__from:date:iso} - ${__to:date:iso}",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \n  DATE_TRUNC('hour', line_item_usage_start_date) AS hour,\n  AVG(CAST(product['vcpu'] AS INT)) AS avg_vcpus\nFROM \n  $CurTable\nWHERE\n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_usage_account_id IN ('$LinkedAccounts')\n  AND product_region_code in ('$Regions')\n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_resource_id LIKE 'i-%'\n  AND line_item_usage_type LIKE ('%Box%')\n  AND product['vcpu'] <> ''\nGROUP BY \n1\nORDER BY\nhour;\n\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "This visual displays the average count/hour of all unique instance IDs observed in the Cost and Usage Report (CUR) for the current selected time period: ${__from:date:iso} - ${__to:date:iso}",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \n  DATE_TRUNC('hour', line_item_usage_start_date) AS hour,\n  COUNT(DISTINCT(line_item_resource_id))\nFROM $CurTable\nWHERE\n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_usage_account_id IN ('$LinkedAccounts')\n  AND product_region_code in ('$Regions')\n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_resource_id LIKE 'i-%'\n  AND line_item_usage_type LIKE ('%Box%')\nGROUP BY\n1\nORDER BY hour DESC;"
    }
   ]
  },
  {
   "title": "EC2: VCPU vs Unblended Cost ",
   "type": "timeseries",
   "description": "This visualization displays two metrics: Cost and Performance. For Cost, it retrieves the total cost for EC2 running CPU from the Cost and Usage Report (CUR) for the specified time period (${CURGranularity}). As for Performance, it pulls the average number of running vCPUs from CloudWatch over the same time period (${CWGranularity} seconds). It's important to ensure that the time periods for the Cost and Usage Report (CUR) and CloudWatch are always aligned.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \n  date_trunc('$CURGranularity', line_item_usage_start_date) as date,\n  SUM(line_item_unblended_cost) AS \"Total EC2 Unblended Cost\"\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_usage_account_id IN ('$LinkedAccounts')\n  AND product_region_code in ('$Regions')\n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type LIKE ('%Box%')\n  AND line_item_line_item_type NOT IN ('Tax')\nGROUP BY\n1\nORDER BY \n  \"Total EC2 Unblended Cost\" DESC;"
    },
    {
     "dimensions": { "Class": "Standard/OnDemand", "Resource": "vCPU", "Service": "EC2", "Type": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Usage,Class,Resource,Service,Type} :aws.AccountId = ${LinkedAccounts} Resource=\\\"vCPU\\\" Service=\\\"EC2\\\"', 'Average', ${CWGranularity} ))",
     "id": "ec2_vcpu_unblended",
     "label": "VCPU",
     "metricEditorMode": 1,
     "metricName": "ResourceCount",
     "namespace": "AWS/Usage",
     "period": "$CWGranularity",
     "queryMode": "Metrics",
     "region": "$Regions",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "sqlExpression": "{\n    \"view\": \"timeSeries\",\n    \"stacked\": false,\n    \"region\": \"us-east-1\",\n    \"metrics\": [\n        [ \"AWS/Usage\", \"CallCount\", \"Type\", \"API\", \"Resource\", \"RunInstances\", \"Service\", \"EC2\", \"Class\", \"None\" ]\n    ]\n}",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "EC2: VCPU vs Amortized Cost ",
   "type": "timeseries",
   "description": "This visualization displays two metrics: Cost and Performance. For Cost, it retrieves the total amortized cost for EC2 running CPU from the Cost and Usage Report (CUR) for the specified time period (${CURGranularity}). As for Performance, it pulls the average number of running vCPUs from CloudWatch over the same time period (${CWGranularity} seconds). It's important to ensure that the time periods for the Cost and Usage Report (CUR) and CloudWatch are always aligned.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \n  date_trunc('$CURGranularity', line_item_usage_start_date) as date,\n  SUM(CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN savings_plan_savings_plan_effective_cost\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN reservation_effective_cost\n    WHEN line_item_line_item_type = 'Usage' THEN line_item_unblended_cost\n    ELSE 0 \n  END) AS \"Total EC2 Amortized Cost\"\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_usage_account_id IN ('$LinkedAccounts')\n  AND product_region_code in ('$Regions')\n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type LIKE ('%Box%')\n  AND line_item_line_item_type NOT IN ('Tax')\nGROUP BY\n1\nORDER BY \n  \"Total EC2 Amortized Cost\" DESC;"
    },
    {
     "dimensions": { "Class": "Standard/OnDemand", "Resource": "vCPU", "Service": "EC2", "Type": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Usage,Class,Resource,Service,Type} :aws.AccountId = ${LinkedAccounts} Resource=\\\"vCPU\\\" Service=\\\"EC2\\\"', 'Average', ${CWGranularity} ))",
     "id": "ec2_vcpu_unblended",
     "label": "VCPU",
     "metricEditorMode": 1,
     "metricName": "ResourceCount",
     "namespace": "AWS/Usage",
     "period": "$CWGranularity",
     "queryMode": "Metrics",
     "region": "$Regions",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "sqlExpression": "{\n    \"view\": \"timeSeries\",\n    \"stacked\": false,\n    \"region\": \"us-east-1\",\n    \"metrics\": [\n        [ \"AWS/Usage\", \"CallCount\", \"Type\", \"API\", \"Resource\", \"RunInstances\", \"Service\", \"EC2\", \"Class\", \"None\" ]\n    ]\n}",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "EC2: VCPU Unblended Unit Cost",
   "type": "timeseries",
   "description": "This visual retrieves the average vcpus running/hour during the CUR granularity of $CURGranularity and the amortized cost per hour from CUR.  The cost is divided by the average vcpus to display the vcpu unit cost for the period: ${__from:date:iso} - ${__to:date:iso}",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "WITH average_vcpu_query AS (\nSELECT \n  date_trunc('$CURGranularity', line_item_usage_start_date) as hour,\n  AVG(CAST(product['vcpu'] AS INT)) AS avg_vcpus\nFROM \n  $CurTable\nWHERE\n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_usage_account_id IN ('$LinkedAccounts')\n  AND product_region_code in ('$Regions')\n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_resource_id LIKE 'i-%'\n  AND line_item_usage_type LIKE ('%Box%')\n  AND product['vcpu'] <> ''\nGROUP BY\n1\nORDER BY\nhour DESC\n), \n\nunblended_cost_query AS (\n  SELECT \n  date_trunc('hour', line_item_usage_start_date) as hour,\n  SUM(CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN savings_plan_savings_plan_effective_cost\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN reservation_effective_cost\n    WHEN line_item_line_item_type = 'Usage' THEN line_item_unblended_cost\n    ELSE 0 \n  END) AS \"Total EC2 Amortized Cost\"\n  --SUM(CAST(line_item_unblended_cost AS DOUBLE)) AS \"Total EC2 Unblended Cost\"\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_usage_account_id IN ('$LinkedAccounts')\n  AND product_region_code in ('$Regions')\n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_line_item_type NOT IN ('Tax')\nGROUP BY\n1\nORDER BY \n  \"Total EC2 Amortized Cost\" DESC\n)\n\nSELECT\nunblended_cost_query.hour as timeperiod,\n(unblended_cost_query.\"Total EC2 Amortized Cost\" / average_vcpu_query.avg_vcpus) as vcpu_unit_cost\nFROM unblended_cost_query\nRIGHT JOIN average_vcpu_query on average_vcpu_query.hour = unblended_cost_query.hour\n\n\n"
    }
   ]
  },
  {
   "title": "EC2 Top 10 Instances by Cost",
   "type": "barchart",
   "description": "This visual retrieves the amortized cost for the top 10 most expensive instance from the Cost and Usage Report (CUR) for the period: ${__from:date:iso} - ${__to:date:iso}",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \n  line_item_resource_id as instance,\n  SUM(CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN savings_plan_savings_plan_effective_cost\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN reservation_effective_cost\n    WHEN line_item_line_item_type = 'Usage' THEN line_item_unblended_cost\n    ELSE 0 \n  END) AS cost\nFROM \n  $CurTable\nWHERE\n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_usage_account_id IN ('$LinkedAccounts')\n  AND product_region_code in ('$Regions')\n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_resource_id LIKE 'i-%'\n  AND line_item_usage_type LIKE ('%Box%')\n  AND product['vcpu'] <> ''\nGROUP BY\n1\nORDER BY \ncost DESC\nLIMIT 10;\n"
    }
   ]
  },
  {
   "title": "Instance Dashboard: $InstanceId",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }
  },
  {
   "title": " Section Overview",
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 38 },
   "options": {
    "content": "<font size=\"2\">\nThis section displays the average compute, disk and network metrics for the current specified instance ${InstanceId}.  The visuals are impacted by selections made from the inpute parameters and the time period.\n\n\n###### Parameters\nCUR Granulairty: ${CURGranularity}     CloudWatch Granulairty: ${CWGranularity}   \n</font>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "EC2: CPU Utilization Vs Cost (${CURGranularity})",
   "type": "timeseries",
   "description": "The first visual displays the instance cost per $CURGranularity from the cost and usage report.  The second visual reports the instance average CPU per ${CWGranularity}(s) for the given time period: ${__from:date:iso} - ${__to:date:iso}",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \n  date_trunc('$CURGranularity', line_item_usage_start_date) as date,\n  SUM(CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN savings_plan_savings_plan_effective_cost\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN reservation_effective_cost\n    WHEN line_item_line_item_type = 'Usage' THEN line_item_unblended_cost\n    ELSE 0 \n  END) AS \"Total Instance Amortized Cost\"\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_resource_id = '$InstanceId'\n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type LIKE ('%Box%')\n  AND line_item_line_item_type NOT IN ('Tax')\nGROUP BY\n1\nORDER BY \n  \"Total Instance Amortized Cost\" DESC;"
    },
    {
     "dimensions": { "InstanceId": "$InstanceId" },
     "expression": "SEARCH('{AWS/EC2,InstanceId} MetricName=\\\"CPUUtilization\\\"  ', 'Average', 300)",
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "period": "$CWGranularity",
     "queryMode": "Metrics",
     "region": "$Regions",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "sqlExpression": "{\n    \"view\": \"timeSeries\",\n    \"stacked\": false,\n    \"region\": \"us-east-1\",\n    \"metrics\": [\n        [ \"AWS/Usage\", \"CallCount\", \"Type\", \"API\", \"Resource\", \"RunInstances\", \"Service\", \"EC2\", \"Class\", \"None\" ]\n    ]\n}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "public rate",
   "type": "stat",
   "description": "Instance type and instance public rate as pulled from the cost and usage report.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \n  line_item_unblended_rate as \"public_rate\",\n  product_instance_type\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_resource_id = '$InstanceId'\n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type LIKE ('%Box%')\n  AND line_item_line_item_type NOT IN ('Tax')\nORDER BY \n  line_item_usage_start_date DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Instance Compute Cost",
   "type": "stat",
   "description": "Total Instance cost for $instanceId for period: ${__from:date:iso} - ${__to:date:iso}",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \n  SUM(CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN savings_plan_savings_plan_effective_cost\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN reservation_effective_cost\n    WHEN line_item_line_item_type = 'Usage' THEN line_item_unblended_cost\n    ELSE 0 \n  END) AS \"Total Instance Amortized Cost\"\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_resource_id = '$InstanceId'\n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_line_item_type NOT IN ('Tax')\nORDER BY \n  \"Total Instance Amortized Cost\" DESC;"
    }
   ]
  },
  {
   "title": "Instance Average CPU Utilization",
   "type": "stat",
   "description": "Average Instance CPU for $instanceId for period: ${__from:date:iso} - ${__to:date:iso}.  \n\nThis field will highlight red if the instance average CPU is < 5% in the given time period.  This indicates the instance may be a candidate for rightsizing based on CPU only.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "InstanceId": "$InstanceId" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "period": "$CWGranularity",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "$InstanceId: NetworkOut Traffic",
   "type": "timeseries",
   "description": "This visual displays data transfer out cost data at a granularity of ${CURGranularity} and CloudWatch Network Out traffic at a CloudWatch granularity of ${CWGranularity}(s) for $InstanceId  during time period: ${__from:date:iso} - ${__to:date:iso}.  \n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expression": "SUM(REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} $InstanceId MetricName=\"NetworkOut\"', 'Sum', $CWGranularity )))/$CWGranularity",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "$Regions",
     "statistic": "Average"
    },
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \n  date_trunc('$CURGranularity', line_item_usage_start_date) as date,\n  SUM(line_item_unblended_cost) as datatransfer_cost\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date)\n  -- AND line_item_resource_id = '$InstanceId'\n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type LIKE ('%DataTransfer-Out%')\n  AND line_item_line_item_type NOT IN ('Tax')\nGROUP BY\n1"
    }
   ]
  },
  {
   "title": "$InstanceId: NetworkIn Traffic",
   "type": "timeseries",
   "description": "This visual displays the Network in traffic for $InstanceId at a CloudWatch granularity of ${CWGranularity}(s) during time period: ${__from:date:iso} - ${__to:date:iso}.  \n\nThere is no charge for incoming network thus we do not display cost and usage data from CUR for NetworkIn",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expression": "SUM(REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} $InstanceId MetricName=\"NetworkIn\"', 'Sum', $CWGranularity )))/$CWGranularity",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "$Regions",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "$InstanceId: Cost by Usage Type",
   "type": "barchart",
   "description": "This visual displays data transfer by usage type for $InstanceId  during time period: ${__from:date:iso} - ${__to:date:iso}.  \n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \n  DISTINCT(line_item_usage_type) as \"Usage Type\",\n  SUM(line_item_unblended_cost) as \"Data Transfer Cost\"\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_resource_id = '$InstanceId'\n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type LIKE ('%DataTransfer-Out%')\n  AND line_item_line_item_type NOT IN ('Tax')\nGROUP BY\n1\nORDER BY\n\"Data Transfer Cost\" DESC"
    }
   ]
  },
  { "title": "Top Instances by Cost", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Top 500 Instances by Cost",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \n  line_item_resource_id as Instance,\n  product_instance_type,\n  CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN 'Savings Plan'\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN 'Reserved Instance'\n    WHEN line_item_line_item_type = 'Usage' THEN 'On Demand'\n    ELSE 'On Demand'\n  END AS \"Purchase Type\",\n  SUM(CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN savings_plan_savings_plan_effective_cost\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN reservation_effective_cost\n    WHEN line_item_line_item_type = 'Usage' THEN line_item_unblended_cost\n    ELSE 0 \n  END) AS Cost\nFROM \n  $CurTable\nWHERE\n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_usage_account_id IN ('$LinkedAccounts')\n  AND product_region_code in ('$Regions')\n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_resource_id LIKE 'i-%'\n  AND line_item_usage_type LIKE ('%Box%')\n  AND product['vcpu'] <> ''\nGROUP BY\n1,2,3\nORDER BY \ncost DESC\nLIMIT 500;\n"
    }
   ]
  }
 ]
}