{
 "title": "Athena Dashboard",
 "time": { "from": "now-7d", "to": "now-1440m" },
 "templating": {
  "list": [
   { "name": "CURDatasource", "label": "CUR Datasource", "query": "grafana-athena-datasource" },
   { "name": "CWDatasource", "label": "CW Datasource", "query": "cloudwatch" },
   { "name": "CURTable", "label": "CUR Table", "query": "cur2" },
   { "name": "CURDatabase", "label": "CUR Database", "query": "cid_data_export" },
   {
    "name": "AccountId",
    "label": "Account ID",
    "query": {}
   },
   {
    "name": "Region",
    "label": "Region",
    "query": {}
   },
   {
    "name": "Workgroup",
    "label": "Workgroup",
    "query": {}
   },
   { "name": "CURGranularity", "label": "CUR Granularity", "query": "hour,day,week,month" },
   { "name": "CWGranularity", "label": "CloudWatch Granularity (s)", "query": "300,3600,86400,604800,2592000" },
   {
    "name": "TagKey",
    "label": "Tag Key",
    "query": {}
   },
   {
    "name": "TagValue",
    "label": "TagValue",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div><h3>Athena Dashboard</h3></div> \n<p>\nThe Athena Dashboard displays AWS Athena cost, usage and performance metric information filtered by account and region. \nOne section also filters by tag. The filter panel will refresh based on selections of previous filters. \nFor example, when an account is selected the Region menu will only show regions, workgroups and tags observed in that account for the time period selected. \n</p>\n\n<div><h5>Section Overview</h5></div>\n<div>\n  <ol>\n<li>Overview Section - A general overview of Athena Spend and related CloudWatch Metrics.</li>\n<li>Tag Explorer - A collection of visuals displaying Cost and Usage grouped by the selected Tag and Value (CloudWatch is not supported with tagging)</li>\n</ol>\n</p>\n\n<p>\nReminder: Change the Athena Database name and Table name in the variables section if you customized these values.  \nThe Athena Database is currently set to **${CURDatabase}**.  The Table is currently set to **${CURTable}**.\n<br><br>\nThis dashboard depends on <a href=\"https://docs.aws.amazon.com/cur/latest/userguide/table-dictionary-cur2.html\" target=\"_blank\">CUR version 2</a> and <a href=\"https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Unified-Cross-Account.html\" target=\"_blank\">CloudWatch (cross-account) metrics</a> being available in the data collection account.  \n</p>\n\n</div>"
   }
  },
  {
   "title": "Athena Overview - ${AccountId} in ${Region}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "Athena Cost for ${AccountId} in ${Region}",
   "type": "timeseries",
   "description": "Athena cost ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date) as line_item_usage_start_date,\nSUM(line_item_unblended_cost) as unblended_cost\nFROM ${CURDatabase}.${CURTable}\nWHERE \n$__timeFilter(line_item_usage_start_date)\nAND line_item_product_code = 'AmazonAthena'\nAND line_item_line_item_type in ('Usage')\nAND line_item_usage_account_id = '${AccountId}'\nAND product_region_code = '${Region}'\nGROUP BY\nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date)\nORDER BY\nline_item_usage_start_date DESC\n"
    }
   ]
  },
  {
   "title": "Athena Total Cost for ${AccountId} in ${Region} - ${__from:date:iso} - ${__to:date:iso}",
   "type": "stat",
   "description": "Athena cost: ${__from:date:iso} - ${__to:date:iso}",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \nSUM(line_item_unblended_cost) AS cost\nFROM ${CURDatabase}.${CURTable}\nWHERE \n$__timeFilter(line_item_usage_start_date)\nAND line_item_product_code = 'AmazonAthena'\nAND line_item_line_item_type in ('Usage')\nAND line_item_usage_account_id = '${AccountId}'\nAND product_region_code = '${Region}';\n\n"
    }
   ]
  },
  {
   "title": "Athena Cost over ProcessedBytes for WorkGroup: ${Workgroup}",
   "type": "timeseries",
   "description": "Athena Cost from CUR for Workgroup: ${Workgroup}. CloudWatch ProcessedBytes measures the number of bytes that Athena scanned per DML query.  Metrics are separated into SUCCEEDED, FAILED, and CANCELED queries. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date) as line_item_usage_start_date,\nSPLIT_PART(SPLIT_PART(line_item_resource_id, ':',  6), '/', 2) as workgroup,\nSUM(line_item_unblended_cost) as unblended_cost\nFROM ${CURDatabase}.${CURTable}\nWHERE \n$__timeFilter(line_item_usage_start_date)\nAND line_item_product_code = 'AmazonAthena'\nAND line_item_line_item_type in ('Usage')\nAND line_item_usage_account_id = '${AccountId}'\nAND product_region_code = '${Region}'\nAND SPLIT_PART(SPLIT_PART(line_item_resource_id, ':',  6), '/', 2) = '${Workgroup}'\nGROUP BY\nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date),\nSPLIT_PART(SPLIT_PART(line_item_resource_id, ':',  6), '/', 2)\nORDER BY\nline_item_usage_start_date DESC\n"
    },
    {
     "accountId": "all",
     "expression": "REMOVE_EMPTY(SEARCH('{\"AWS/Athena\",\"QueryState\",\"QueryType\",\"WorkGroup\"} \"ProcessedBytes\" WorkGroup=\"${Workgroup}\" :aws.AccountId=\"${AccountId}\"', 'Average', ${CWGranularity}))",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Athena Spend by workgroup in  ${AccountId} in ${Region} - ${__from:date:iso} - ${__to:date:iso}",
   "type": "barchart",
   "description": "Athena Spend by workgroup in  ${AccountId} in ${Region} - ${__from:date:iso} - ${__to:date:iso}",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT DISTINCT \n    SPLIT_PART(SPLIT_PART(line_item_resource_id, ':', 6), '/', 2) as workgroup,\n    SUM(line_item_unblended_cost) as cost\nFROM ${CURDatabase}.${CURTable}\nWHERE \n$__timeFilter(line_item_usage_start_date)\nAND line_item_product_code = 'AmazonAthena'\nAND line_item_line_item_type in ('Usage')\nAND line_item_usage_account_id = '${AccountId}'\nAND product_region_code = '${Region}'\nGROUP BY\nSPLIT_PART(SPLIT_PART(line_item_resource_id, ':', 6), '/', 2)\nORDER BY \nworkgroup DESC;"
    }
   ]
  },
  {
   "title": "Athena TotalExecutionTime for WorkGroup: ${Workgroup}",
   "type": "timeseries",
   "description": "The number of milliseconds that Athena took to run a DDL or DML query.  for Workgroup: ${Workgroup}",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "accountId": "all",
     "expression": "REMOVE_EMPTY(SEARCH('{\"AWS/Athena\",\"QueryState\",\"QueryType\",\"WorkGroup\"} \"TotalExecutionTime\" WorkGroup=\"${Workgroup}\" :aws.AccountId=\"${AccountId}\"', 'Average', ${CWGranularity}))",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Athena QueryQueueTime for WorkGroup: ${Workgroup}",
   "type": "timeseries",
   "description": "The number of milliseconds that the query was in the query queue waiting for resources for Workgroup: ${Workgroup}",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "accountId": "all",
     "expression": "REMOVE_EMPTY(SEARCH('{\"AWS/Athena\",\"QueryState\",\"QueryType\",\"WorkGroup\"} \"QueryQueueTime\" WorkGroup=\"${Workgroup}\" :aws.AccountId=\"${AccountId}\"', 'Average', ${CWGranularity}))",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Athena Total Capacity Reservation Cost over Capacity Reservation Metrics for ${AccountId} in ${Region}",
   "type": "timeseries",
   "description": "Athena Cost from CUR for Workgroup: ${Workgroup}. \nCloudWatch DPUAllocated capacity reservation allocated per reservation.  \nDPUConsumed capacity reservation per workgroup measures the number of bytes that Athena scanned per DML query in the capacity reservation.  ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date) as line_item_usage_start_date,\nSPLIT_PART(SPLIT_PART(line_item_resource_id, ':',  6), '/', 2) as workgroup,\nSUM(line_item_unblended_cost) as unblended_cost\nFROM ${CURDatabase}.${CURTable}\nWHERE \n$__timeFilter(line_item_usage_start_date)\nAND line_item_product_code = 'AmazonAthena'\nAND line_item_line_item_type in ('Usage')\nAND line_item_usage_type LIKE '%ReservedCapacityInDPUHours'\nAND line_item_usage_account_id = '${AccountId}'\nAND product_region_code = '${Region}'\n-- AND SPLIT_PART(SPLIT_PART(line_item_resource_id, ':',  6), '/', 2) = '${Workgroup}'\nGROUP BY\nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date),\nSPLIT_PART(SPLIT_PART(line_item_resource_id, ':',  6), '/', 2)\nORDER BY\nline_item_usage_start_date DESC\n"
    },
    {
     "accountId": "all",
     "expression": "REMOVE_EMPTY(SEARCH('{\"AWS/Athena\",\"Capacity Reservation\"} \"DPUAllocated\" :aws.AccountId=\"${AccountId}\"', 'Average', ${CWGranularity}))",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Average"
    },
    {
     "accountId": "all",
     "expression": "REMOVE_EMPTY(SEARCH('{\"AWS/Athena\",\"WorkGroup\",\"Capacity Reservation\"} \"DPUConsumed\" WorkGroup=\"${Workgroup}\" :aws.AccountId=\"${AccountId}\"', 'Average', ${CWGranularity}))",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Tag Explorer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Athena Cost for ${AccountId} in ${Region} -  Tag: (${TagKey}, ${TagValue})",
     "type": "timeseries",
     "description": "Athena cost -  Tag: (${TagKey}, ${TagValue})",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "SELECT \nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date) as line_item_usage_start_date,\nSPLIT_PART(SPLIT_PART(line_item_resource_id, ':',  6), '/', 2) as workgroup,\nSUM(line_item_unblended_cost) as unblended_cost\nFROM ${CURDatabase}.${CURTable}\nWHERE \n$__timeFilter(line_item_usage_start_date)\nAND line_item_product_code = 'AmazonAthena'\nAND line_item_line_item_type in ('Usage')\nAND line_item_usage_account_id = '${AccountId}'\nAND product_region_code = '${Region}'\nAND resource_tags['${TagKey}'] = '${TagValue}'\nGROUP BY\nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date),\nSPLIT_PART(SPLIT_PART(line_item_resource_id, ':',  6), '/', 2)\nORDER BY\nline_item_usage_start_date DESC\n"
      }
     ]
    },
    {
     "title": "Athena Cost for ${AccountId} in ${Region} -  Tag: (${TagKey}, ${TagValue}) ",
     "type": "stat",
     "description": "Athena cost -  Tag: (${TagKey}, ${TagValue}) -  ${__from:date:iso} - ${__to:date:iso}",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "SELECT \nSUM(line_item_unblended_cost) AS cost\nFROM ${CURDatabase}.${CURTable}\nWHERE \n$__timeFilter(line_item_usage_start_date)\nAND line_item_product_code = 'AmazonAthena'\nAND line_item_line_item_type in ('Usage')\nAND line_item_usage_account_id = '${AccountId}'\nAND product_region_code = '${Region}'\nAND resource_tags['${TagKey}'] = '${TagValue}';\n\n"
      }
     ]
    }
   ]
  }
 ]
}