{
 "title": "EC2 Dashboard",
 "time": { "from": "now-7d", "to": "now-1440m" },
 "templating": {
  "list": [
   { "name": "CURDatasource", "label": "CUR Datasource", "query": "grafana-athena-datasource" },
   { "name": "CWDatasource", "label": "CW Datasource", "query": "cloudwatch" },
   { "name": "CURTable", "label": "CUR Table", "query": "cur2" },
   { "name": "CURDatabase", "label": "CUR Database", "query": "cid_data_export" },
   {
    "name": "AccountId",
    "label": "Account ID",
    "query": {}
   },
   {
    "name": "Region",
    "label": "Region",
    "query": {}
   },
   {
    "name": "InstanceId",
    "label": "Instance ID",
    "query": {}
   },
   { "name": "CURGranularity", "label": "CUR Granularity", "query": "hour,day,week,month" },
   { "name": "CWGranularity", "label": "CloudWatch Granularity(s)", "query": "300,3600,86400,604800,2592000" },
   {
    "name": "TagKey",
    "label": "Tag Key",
    "query": {}
   },
   {
    "name": "TagValue",
    "label": "TagValue",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div><h3>EC2 Instance Dashboard</h3></div> \n<p>\nThe EC2 Instance Dashboard displays EC2 instance compute cost, usage and performance metric information filtered by account and region.  One section also filters by tag.  \nThe filter panel will refresh based on selections of previous filters.  For example, when an account is selected the Region menu will only show regions, \ninstances and tags observed in that account for the time period selected.\n<br><br>\nCloudWatch metrics are available in certain graphs where a common key can be defined between CUR data and CloudWatch data (i.e. instance name).  For metrics \nto work correctly, you need the CloudWatch data source enabled.  For CloudWatch cross-account/cross-region to work correctly you need to have <a href=\"https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Unified-Cross-Account.html\" target=\"_blank\">CloudWatch (cross-account) metrics</a>\nconfigured.\n</p>\n\n<div><h5>Section Overview</h5></div>\n<div>\n<p>\n  <ol>\n<li>Overview Section - A general overview of EC2 Spend.</li>\n<li>Tag Explorer - A collection of visuals displaying Cost and Usage grouped by the selected Tag and Value (CloudWatch is not supported with tagging)</li>\n<li>Instance Explorer -  A collection of visuals displaying Cost and Usage over CloudWatch Metrics for the selected instance</li>\n</ol>\n</p>\n\n<p>\nReminder: Change the Athena Database name and Table name in the variables section if you customized these values.  \nThe Athena Database is currently set to **${CURDatabase}**.  The Table is currently set to **${CURTable}**.\n<br><br>\nThis dashboard depends on <a href=\"https://docs.aws.amazon.com/cur/latest/userguide/table-dictionary-cur2.html\" target=\"_blank\">CUR version 2</a> and <a href=\"https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Unified-Cross-Account.html\" target=\"_blank\">CloudWatch (cross-account) metrics</a> being available in the data collection account.  \n</p>\n</div>"
   }
  },
  {
   "title": "EC2 Compute Overview - ${AccountId} in ${Region}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "EC2 Compute Cost for ${AccountId} in ${Region}",
     "type": "timeseries",
     "description": "Amortized cost for  EC2 Compute ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "SELECT \nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date) as line_item_usage_start_date,\nSUM(CAST(product['vcpu'] as int)) as number_of_vcpu,\nSUM(CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN savings_plan_savings_plan_effective_cost\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN reservation_effective_cost\n    WHEN line_item_line_item_type = 'Usage' THEN line_item_unblended_cost\n    ELSE 0 \n  END) AS amortized_cost\nFROM ${CURDatabase}.${CURTable}\nWHERE \n$__timeFilter(line_item_usage_start_date)\nAND line_item_product_code = 'AmazonEC2' \nAND line_item_operation LIKE '%RunInstances%' \nAND line_item_usage_type NOT LIKE '%DataXfer%' \nAND product_servicecode <> 'AWSDataTransfer' \nAND line_item_resource_id NOT LIKE 'arn:%:capacity-reservation/%'\nAND line_item_line_item_type in ('SavingsPlanCoveredUsage', 'Usage', 'DiscountedUsage')\nAND line_item_usage_account_id = '${AccountId}'\nAND product_region_code = '${Region}'\nGROUP BY\nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date)\nORDER BY\nline_item_usage_start_date DESC\n"
      }
     ]
    },
    {
     "title": "EC2 Compute Cost for ${AccountId} in ${Region} - ${__from:date:iso} - ${__to:date:iso}",
     "type": "stat",
     "description": "Amortized cost includes EC2 Compute: ${__from:date:iso} - ${__to:date:iso}",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "SELECT \nSUM(CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN savings_plan_savings_plan_effective_cost\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN reservation_effective_cost\n    WHEN line_item_line_item_type = 'Usage' THEN line_item_unblended_cost\n    ELSE 0 \n  END) AS amortized_cost\nFROM ${CURDatabase}.${CURTable}\nWHERE \n$__timeFilter(line_item_usage_start_date)\nAND line_item_product_code = 'AmazonEC2' \nAND line_item_operation LIKE '%RunInstances%' \nAND line_item_usage_type NOT LIKE '%DataXfer%' \nAND product_servicecode <> 'AWSDataTransfer' \nAND line_item_resource_id NOT LIKE 'arn:%:capacity-reservation/%'\nAND line_item_line_item_type in ('SavingsPlanCoveredUsage', 'Usage', 'DiscountedUsage')\nAND line_item_usage_account_id = '${AccountId}'\nAND product_region_code = '${Region}';\n\n"
      }
     ]
    },
    {
     "title": "EC2 Compute cost by purchase type for ${AccountId} in ${Region}",
     "type": "timeseries",
     "description": "Amortized cost for  EC2 Compute ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "SELECT \nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date) as line_item_usage_start_date,\nSUM(CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN savings_plan_savings_plan_effective_cost\n    ELSE 0 \n  END) AS savings_plan_spend,\nSUM(CASE\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN reservation_effective_cost\n    ELSE 0 \n  END) AS reserved_instance_spend,\nSUM(CASE\n    WHEN line_item_line_item_type = 'Usage' THEN line_item_unblended_cost\n    ELSE 0 \n  END) AS ondemand_spend\nFROM ${CURDatabase}.${CURTable}\nWHERE \n$__timeFilter(line_item_usage_start_date)\nAND line_item_product_code = 'AmazonEC2' \nAND line_item_operation LIKE '%RunInstances%' \nAND line_item_usage_type NOT LIKE '%DataXfer%' \nAND product_servicecode <> 'AWSDataTransfer' \nAND line_item_resource_id NOT LIKE 'arn:%:capacity-reservation/%'\nAND line_item_line_item_type in ('SavingsPlanCoveredUsage', 'Usage', 'DiscountedUsage')\nAND line_item_usage_account_id = '${AccountId}'\nAND product_region_code = '${Region}'\nGROUP BY\nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date)\nORDER BY\nline_item_usage_start_date DESC\n"
      }
     ]
    },
    {
     "title": "Comput Spend by Instance Type in  ${AccountId} in ${Region}",
     "type": "barchart",
     "description": "Top 10 instance types",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "SELECT \nproduct_instance_type,\nSUM(CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN savings_plan_savings_plan_effective_cost\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN reservation_effective_cost\n    WHEN line_item_line_item_type = 'Usage' THEN line_item_unblended_cost\n    ELSE 0 \n  END) AS amortized_cost\nFROM ${CURDatabase}.${CURTable}\nWHERE \n$__timeFilter(line_item_usage_start_date)\nAND line_item_product_code = 'AmazonEC2' \nAND line_item_operation LIKE '%RunInstances%' \nAND line_item_usage_type NOT LIKE '%DataXfer%' \nAND product_servicecode <> 'AWSDataTransfer' \nAND line_item_resource_id NOT LIKE 'arn:%:capacity-reservation/%'\nAND line_item_line_item_type in ('SavingsPlanCoveredUsage', 'Usage', 'DiscountedUsage')\nAND line_item_usage_account_id = '${AccountId}'\nAND product_region_code = '${Region}'\nGROUP BY\nproduct_instance_type\nORDER BY \namortized_cost DESC\nLIMIT 10;\n"
      }
     ]
    },
    {
     "title": "Top 100 Instances by Cost",
     "type": "table",
     "description": "Top 100 Instance by amortized cost for time period",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "SELECT\nline_item_resource_id as instance_id,\nSUM(CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN savings_plan_savings_plan_effective_cost\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN reservation_effective_cost\n    WHEN line_item_line_item_type = 'Usage' THEN line_item_unblended_cost\n    ELSE 0 \n  END) AS amortized_cost\nFROM ${CURDatabase}.${CURTable}\nWHERE \n$__timeFilter(line_item_usage_start_date) \nAND line_item_product_code = 'AmazonEC2' \nAND line_item_operation LIKE '%RunInstances%' \nAND line_item_usage_type NOT LIKE '%DataXfer%' \nAND product_servicecode <> 'AWSDataTransfer' \nAND line_item_resource_id NOT LIKE 'arn:%:capacity-reservation/%'\nAND line_item_line_item_type in ('SavingsPlanCoveredUsage', 'Usage', 'DiscountedUsage')\nAND line_item_usage_account_id = '${AccountId}'\nAND product_region_code = '${Region}'\nGROUP BY\nline_item_resource_id\nORDER BY\namortized_cost DESC\nLIMIT 100"
      }
     ]
    }
   ]
  },
  {
   "title": "Tag Explorer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "EC2 Compute Cost for ${AccountId} in ${Region} -  Tag: (${TagKey}, ${TagValue})",
     "type": "timeseries",
     "description": "Amortized cost for  EC2 Compute ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "SELECT \nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date) as line_item_usage_start_date,\nSUM(CAST(product['vcpu'] as int)) as number_of_vcpu,\nSUM(CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN savings_plan_savings_plan_effective_cost\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN reservation_effective_cost\n    WHEN line_item_line_item_type = 'Usage' THEN line_item_unblended_cost\n    ELSE 0 \n  END) AS amortized_cost\nFROM ${CURDatabase}.${CURTable}\nWHERE \n$__timeFilter(line_item_usage_start_date)\nAND line_item_product_code = 'AmazonEC2' \nAND line_item_operation LIKE '%RunInstances%' \nAND line_item_usage_type NOT LIKE '%DataXfer%' \nAND product_servicecode <> 'AWSDataTransfer' \nAND line_item_resource_id NOT LIKE 'arn:%:capacity-reservation/%'\nAND line_item_line_item_type in ('SavingsPlanCoveredUsage', 'Usage', 'DiscountedUsage')\nAND line_item_usage_account_id = '${AccountId}'\nAND product_region_code = '${Region}'\nAND resource_tags['${TagKey}'] = '${TagValue}'\nGROUP BY\nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date)\nORDER BY\nline_item_usage_start_date DESC\n"
      }
     ]
    },
    {
     "title": "EC2 Compute Cost for ${AccountId} in ${Region} -  Tag: (${TagKey}, ${TagValue})",
     "type": "stat",
     "description": "Amortized cost includes EC2 Compute: ${__from:date:iso} - ${__to:date:iso}",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "SELECT \nSUM(CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN savings_plan_savings_plan_effective_cost\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN reservation_effective_cost\n    WHEN line_item_line_item_type = 'Usage' THEN line_item_unblended_cost\n    ELSE 0 \n  END) AS amortized_cost\nFROM ${CURDatabase}.${CURTable}\nWHERE \n$__timeFilter(line_item_usage_start_date)\nAND line_item_product_code = 'AmazonEC2' \nAND line_item_operation LIKE '%RunInstances%' \nAND line_item_usage_type NOT LIKE '%DataXfer%' \nAND product_servicecode <> 'AWSDataTransfer' \nAND line_item_resource_id NOT LIKE 'arn:%:capacity-reservation/%'\nAND line_item_line_item_type in ('SavingsPlanCoveredUsage', 'Usage', 'DiscountedUsage')\nAND line_item_usage_account_id = '${AccountId}'\nAND product_region_code = '${Region}'\nAND resource_tags['${TagKey}'] = '${TagValue}';\n\n"
      }
     ]
    },
    {
     "title": "EC2 Compute cost by purchase type for ${AccountId} in ${Region} -  Tag: (${TagKey}, ${TagValue})",
     "type": "timeseries",
     "description": "Amortized cost for  EC2 Compute ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "SELECT \nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date) as line_item_usage_start_date,\nSUM(CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN savings_plan_savings_plan_effective_cost\n    ELSE 0 \n  END) AS savings_plan_spend,\nSUM(CASE\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN reservation_effective_cost\n    ELSE 0 \n  END) AS reserved_instance_spend,\nSUM(CASE\n    WHEN line_item_line_item_type = 'Usage' THEN line_item_unblended_cost\n    ELSE 0 \n  END) AS ondemand_spend\nFROM ${CURDatabase}.${CURTable}\nWHERE \n$__timeFilter(line_item_usage_start_date)\nAND line_item_product_code = 'AmazonEC2' \nAND line_item_operation LIKE '%RunInstances%' \nAND line_item_usage_type NOT LIKE '%DataXfer%' \nAND product_servicecode <> 'AWSDataTransfer' \nAND line_item_resource_id NOT LIKE 'arn:%:capacity-reservation/%'\nAND line_item_line_item_type in ('SavingsPlanCoveredUsage', 'Usage', 'DiscountedUsage')\nAND line_item_usage_account_id = '${AccountId}'\nAND product_region_code = '${Region}'\nAND resource_tags['${TagKey}'] = '${TagValue}'\nGROUP BY\nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date)\nORDER BY\nline_item_usage_start_date DESC\n\n"
      }
     ]
    },
    {
     "title": "Comput Spend by Instance Type in  ${AccountId} in ${Region} - Tag: (${TagKey}, ${TagValue})",
     "type": "barchart",
     "description": "Top 10 instance types - ${__from:date:iso} - ${__to:date:iso}\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "SELECT \nproduct_instance_type,\nSUM(CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN savings_plan_savings_plan_effective_cost\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN reservation_effective_cost\n    WHEN line_item_line_item_type = 'Usage' THEN line_item_unblended_cost\n    ELSE 0 \n  END) AS amortized_cost\nFROM ${CURDatabase}.${CURTable}\nWHERE \n$__timeFilter(line_item_usage_start_date)\nAND line_item_product_code = 'AmazonEC2' \nAND line_item_operation LIKE '%RunInstances%' \nAND line_item_usage_type NOT LIKE '%DataXfer%' \nAND product_servicecode <> 'AWSDataTransfer' \nAND line_item_resource_id NOT LIKE 'arn:%:capacity-reservation/%'\nAND line_item_line_item_type in ('SavingsPlanCoveredUsage', 'Usage', 'DiscountedUsage')\nAND line_item_usage_account_id = '${AccountId}'\nAND product_region_code = '${Region}'\nAND resource_tags['${TagKey}'] = '${TagValue}'\nGROUP BY\nproduct_instance_type\nORDER BY \namortized_cost DESC\nLIMIT 10;\n"
      }
     ]
    },
    {
     "title": "Top 100 Instances by Cost - Tag: (${TagKey}, ${TagValue})",
     "type": "table",
     "description": "Top 100 Instance by amortized cost for time period",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "SELECT\nline_item_resource_id as instance_id,\nSUM(CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN savings_plan_savings_plan_effective_cost\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN reservation_effective_cost\n    WHEN line_item_line_item_type = 'Usage' THEN line_item_unblended_cost\n    ELSE 0 \n  END) AS amortized_cost\nFROM ${CURDatabase}.${CURTable}\nWHERE \n$__timeFilter(line_item_usage_start_date) \nAND line_item_product_code = 'AmazonEC2' \nAND line_item_operation LIKE '%RunInstances%' \nAND line_item_usage_type NOT LIKE '%DataXfer%' \nAND product_servicecode <> 'AWSDataTransfer' \nAND line_item_resource_id NOT LIKE 'arn:%:capacity-reservation/%'\nAND line_item_line_item_type in ('SavingsPlanCoveredUsage', 'Usage', 'DiscountedUsage')\nAND line_item_usage_account_id = '${AccountId}'\nAND product_region_code = '${Region}'\nAND resource_tags['${TagKey}'] = '${TagValue}'\nGROUP BY\nline_item_resource_id\nORDER BY\namortized_cost DESC\nLIMIT 100"
      }
     ]
    }
   ]
  },
  {
   "title": "Instance Explorer - ${InstanceId}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU over Cost - ${InstanceId}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "SELECT \nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date) as line_item_usage_start_date,\nSUM(CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN savings_plan_savings_plan_effective_cost\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN reservation_effective_cost\n    WHEN line_item_line_item_type = 'Usage' THEN line_item_unblended_cost\n    ELSE 0 \n  END) AS amortized_cost\nFROM ${CURDatabase}.${CURTable}\nWHERE \n$__timeFilter(line_item_usage_start_date)\nAND line_item_product_code = 'AmazonEC2' \nAND line_item_operation LIKE '%RunInstances%' \nAND line_item_usage_type NOT LIKE '%DataXfer%' \nAND product_servicecode <> 'AWSDataTransfer' \nAND line_item_resource_id NOT LIKE 'arn:%:capacity-reservation/%'\nAND line_item_line_item_type in ('SavingsPlanCoveredUsage', 'Usage', 'DiscountedUsage')\nAND line_item_usage_account_id = '${AccountId}'\nAND product_region_code = '${Region}'\nAND line_item_resource_id = '${InstanceId}'\nGROUP BY\nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date)\nORDER BY\nline_item_usage_start_date DESC\n"
      },
      {
       "expression": "REMOVE_EMPTY(SEARCH('{\"AWS/EC2\",\"InstanceId\"} MetricName=\"CPUUtilization\" InstanceId=\"${InstanceId}\" :aws.AccountId=\"${AccountId}\"', 'Average', ${CWGranularity}))",
       "metricEditorMode": 1,
       "queryMode": "Metrics",
       "region": "$Region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Instance Types",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "SELECT \nproduct_instance_type\nFROM ${CURDatabase}.${CURTable}\nWHERE \n$__timeFilter(line_item_usage_start_date)\nAND line_item_product_code = 'AmazonEC2' \nAND line_item_operation LIKE '%RunInstances%' \nAND line_item_usage_type NOT LIKE '%DataXfer%' \nAND product_servicecode <> 'AWSDataTransfer' \nAND line_item_resource_id NOT LIKE 'arn:%:capacity-reservation/%'\nAND line_item_line_item_type in ('SavingsPlanCoveredUsage', 'Usage', 'DiscountedUsage')\nAND line_item_usage_account_id = '${AccountId}'\nAND product_region_code = '${Region}'\nAND line_item_resource_id = '${InstanceId}'\nGROUP BY\nproduct_instance_type\n\n"
      }
     ]
    },
    {
     "title": "Instance Purchase Types",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "\nSELECT \n  DISTINCT\n  CASE\n    WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN 'Savings Plan'\n    WHEN line_item_line_item_type = 'DiscountedUsage' THEN 'Reserved Instance'\n    WHEN line_item_line_item_type = 'Usage' THEN 'On Demand'\n    ELSE 'Other'\n  END\nFROM \n  ${CURDatabase}.${CURTable}\nWHERE \n$__timeFilter(line_item_usage_start_date)\nAND line_item_product_code = 'AmazonEC2' \nAND line_item_operation LIKE '%RunInstances%' \nAND line_item_usage_type NOT LIKE '%DataXfer%' \nAND product_servicecode <> 'AWSDataTransfer' \nAND line_item_resource_id NOT LIKE 'arn:%:capacity-reservation/%'\nAND line_item_line_item_type in ('SavingsPlanCoveredUsage', 'Usage', 'DiscountedUsage')\nAND line_item_usage_account_id = '${AccountId}'\nAND product_region_code = '${Region}'\nAND line_item_resource_id = '${InstanceId}'\n"
      }
     ]
    },
    {
     "title": "CPU over Usage -  ${InstanceId}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "SELECT \nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date) as line_item_usage_start_date,\nSUM(line_item_usage_amount) as sum_line_item_usage_amount\nFROM ${CURDatabase}.${CURTable}\nWHERE \n$__timeFilter(line_item_usage_start_date)\nAND line_item_product_code = 'AmazonEC2' \nAND line_item_operation LIKE '%RunInstances%' \nAND line_item_usage_type NOT LIKE '%DataXfer%' \nAND product_servicecode <> 'AWSDataTransfer' \nAND line_item_resource_id NOT LIKE 'arn:%:capacity-reservation/%'\nAND line_item_line_item_type in ('SavingsPlanCoveredUsage', 'Usage', 'DiscountedUsage')\nAND line_item_usage_account_id = '${AccountId}'\nAND product_region_code = '${Region}'\nAND line_item_resource_id = '${InstanceId}'\nGROUP BY\nline_item_usage_start_date\nORDER BY\nline_item_usage_start_date DESC\n"
      },
      {
       "expression": "REMOVE_EMPTY(SEARCH('{\"AWS/EC2\",\"InstanceId\"} \"CPUUtilization\" InstanceId=\"${InstanceId}\" :aws.AccountId=\"${AccountId}\"', 'Average', ${CWGranularity}))",
       "metricEditorMode": 1,
       "queryMode": "Metrics",
       "region": "us-east-1",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Network Out over Data Transfer Out Cost - ${InstanceId}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "SELECT \nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date) as line_item_usage_start_date,\nSUM(line_item_unblended_cost) as sum_line_item_unblended_cost\nFROM ${CURDatabase}.${CURTable}\nWHERE \n$__timeFilter(line_item_usage_start_date)\nAND line_item_product_code = 'AmazonEC2'\nAND line_item_usage_type LIKE '%DataTransfer-Out-Bytes'\nAND line_item_line_item_type in ('SavingsPlanCoveredUsage', 'Usage', 'DiscountedUsage')\nAND line_item_usage_account_id = '${AccountId}'\nAND product_region_code = '${Region}'\nAND line_item_resource_id = '${InstanceId}'\nGROUP BY\nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date)\nORDER BY\nline_item_usage_start_date DESC\n"
      },
      {
       "expression": "REMOVE_EMPTY(SEARCH('{\"AWS/EC2\",\"InstanceId\"} \"NetworkOut\" InstanceId=\"${InstanceId}\" :aws.AccountId=\"${AccountId}\"', 'Average', ${CWGranularity}))",
       "metricEditorMode": 1,
       "queryMode": "Metrics",
       "region": "us-east-1",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Network Out over Data Transfer Regional  Cost - ${InstanceId}",
     "type": "timeseries",
     "description": "Absence of cost may mean the instance is in the free teir",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "SELECT \nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date) as line_item_usage_start_date,\nSUM(line_item_unblended_cost) as sum_line_item_unblended_cost\nFROM ${CURDatabase}.${CURTable}\nWHERE \n$__timeFilter(line_item_usage_start_date)\nAND line_item_product_code = 'AmazonEC2'\nAND line_item_usage_type LIKE '%DataTransfer-Regional-Bytes'\nAND line_item_line_item_type in ('SavingsPlanCoveredUsage', 'Usage', 'DiscountedUsage')\nAND line_item_usage_account_id = '${AccountId}'\nAND product_region_code = '${Region}'\nAND line_item_resource_id = '${InstanceId}'\nGROUP BY\nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date)\nORDER BY\nline_item_usage_start_date DESC\n"
      },
      {
       "expression": "REMOVE_EMPTY(SEARCH('{\"AWS/EC2\",\"InstanceId\"} \"NetworkOut\" InstanceId=\"${InstanceId}\" :aws.AccountId=\"${AccountId}\"', 'Average', ${CWGranularity}))",
       "metricEditorMode": 1,
       "queryMode": "Metrics",
       "region": "us-east-1",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Network Out over Intra-Region Data Transfer Cost - ${InstanceId}",
     "type": "timeseries",
     "description": "Transfer between regions from resource.  Absence of cost may mean the instance is covered under the free tier.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "SELECT \nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date) as line_item_usage_start_date,\nSUM(line_item_unblended_cost) as sum_line_item_unblended_cost\nFROM ${CURDatabase}.${CURTable}\nWHERE \n$__timeFilter(line_item_usage_start_date)\nAND line_item_product_code = 'AmazonEC2'\nAND line_item_usage_type LIKE '%-AWS-In-Bytes'\nAND line_item_line_item_type in ('SavingsPlanCoveredUsage', 'Usage', 'DiscountedUsage')\nAND line_item_usage_account_id = '${AccountId}'\nAND product_region_code = '${Region}'\nAND line_item_resource_id = '${InstanceId}'\nGROUP BY\nDATE_TRUNC('${CURGranularity}', line_item_usage_start_date)\nORDER BY\nline_item_usage_start_date DESC\n"
      },
      {
       "expression": "REMOVE_EMPTY(SEARCH('{\"AWS/EC2\",\"InstanceId\"} \"NetworkOut\" InstanceId=\"${InstanceId}\" :aws.AccountId=\"${AccountId}\"', 'Average', ${CWGranularity}))",
       "metricEditorMode": 1,
       "queryMode": "Metrics",
       "region": "us-east-1",
       "statistic": "Average"
      }
     ]
    }
   ]
  }
 ]
}