{
 "title": "Autoscaling Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "CurTable",
    "label": "Cur Table",
    "query": {}
   },
   {
    "name": "Regions",
    "label": "Regions",
    "query": {}
   },
   {
    "name": "LinkedAccounts",
    "label": "Linked Accounts",
    "query": {}
   },
   { "name": "ASGName", "label": "ASG Name" },
   {
    "name": "TagKey",
    "label": "Tag Key",
    "query": {}
   },
   {
    "name": "TagValue",
    "label": "Tag Value",
    "query": {}
   },
   {
    "name": "NGWName",
    "label": "NatGatway",
    "query": {}
   },
   {
    "name": "LBName",
    "label": "Load Balancer",
    "query": {}
   },
   { "name": "Granularity", "label": "Granularity", "query": "month,week,day,hour" }
  ]
 },
 "panels": [
  { "title": "Instructions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "<span style='color: #AF69EE;font-size:20px'>Auto Scaling Dashboard</span>\n<br><br>\n<p>\nThe <span style='color: #AF69EE'>Auto Scaling Dashboard</span> leverages <span style='color: #FF9900'>\nCloudWatch</span> metrics and <span style='color: #FF9900'>Cost and Usage Report (CUR)</span> data to \npresent comprehensive cost over performance metric visualizations. It includes vital components such as \nAuto Scaling Groups (ASG), Load Balancers, NAT Gateways, and EC2 Instances that operate within the ASG.\nAll of these resource must share one common tag.  This tag must also be enabled as a \n<span style='color: #FF9900'>Cost Allocation Tag</span>.\n</p>\n\n<p>\nThis dashboard presents all cost information as <span style='color: #FF9900'>unblended cost</span> and \nwill not reflect discount savings realized by Savings Plans or Reserved Instances.\n</p>\n\n<p>\nFor any inquiries or further assistance in interpreting the data or utilizing the dashboard's features, \nplease contact your assigned Cloud Financial Analyst or FinOps Manager for guidance and support.\n</p>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "options": {
    "content": "<div style='font-size: 18px'>\nHow to Utilize this Dashboard\n</div>\nFor additional instructions see the <a href=\"https://github.com/aws-samples/coast-grafana-cost-intelligence-dashboards/tree/main/grafana_dashboards/auto_scaling\" target=\"_blank\">Github Readme file</a>.<br><br>\n\nTo make the most of the <span style='color: #AF69EE'>Autoscaling Dashboard</span>, input the following parameters in the top parameter menu:\n<br><br>\n\n<ol>\n<li>Region: Select your region (note in the beta version of this dashboard only us-east-1 is supported).</li>\n\n<li>ASG Name: Fill in the name of your Auto Scaling Group (ASG).  The name is available on the ASG details page under \"Group Details\".</li>\n\n<li>Tags: Select the tag key for your resources.  The tag values will populate once the tag key is selected. The values for this drop down come from CUR with a lookback period of 3 days.</li>\n\n<li>Load Balancers: This drop down is populated automtically once you select your tag.  The values for this drop down come from CUR with a lookback period of 3 days.</li>\n\n<li>Nat Gateways: This drop down is populated automtically once you select your tag.  The values for this drop down come from CUR with a lookback period of 3 days.</li>\n\n<li>Granularity: This value is used only in CUR querys to smooth out data based on month, week, day or hour.  To match Cloudwatch, select hour.</li>\n</ol>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": {
    "content": "The <span style='color: #AF69EE'>Required Columns Validator</span> evaluates your CUR dataset to confirm the presence of essential columns. For the dashboard to operate accurately, the CUR dataset must include columns for:\n<br><br>\n<ul>\n  <li>Resource IDs - </li>Resource IDs rows in CUR help deep dive cost at the resource ARNs layer.  To setup your CUR with resource IDs see <a href=\"https://docs.aws.amazon.com/cur/latest/userguide/cur-create.html\">Creating Cost and Usage Report</a>\n  <li>Cost Allocation Tags - Defining a cost allocation tag results in its persistence in your CUR dataset. For our queries to function correctly, it is imperative to have at least one cost allocation tag enabled.  See <a href=\"https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/cost-alloc-tags.html\">Using Cost Allocation Tags</a>\n</ul>\n<br>\n<span style='color: #AF69EE'>VERIFIED</span> indicates the presence of the columns in your CUR. <span style='color: red'>FAILED</span> indicates the absence of these columns, and as a result, certain visuals in the dashboard may not function as expected.  If this is a new CUR it may take 24 hours for column data to populate."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "CUR Columns Validator",
   "type": "table",
   "description": "This table will display TRUE if the required savings plans, reservation and cost allocation columns exist within your dataset.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "with user_tag_columns as ( -- count cost allocation tags\nSELECT \nCOUNT(*) OVER (PARTITION BY column_name) AS user_tag_column_count\nFROM information_schema.columns\nWHERE \ntable_name = '$CurTable'\nAND column_name LIKE 'resource_tags_user_%'  \n),\n\nresource_columns_query as ( -- check for savings plans column\nSELECT \nCOUNT(*) OVER (PARTITION BY column_name) AS resource_column_count\nFROM information_schema.columns\nWHERE \ntable_name = '$CurTable'\nAND column_name = 'line_item_resource_id'  \n)\n\nSELECT \nCASE\n    WHEN (SELECT SUM(user_tag_column_count) FROM user_tag_columns) > 0 THEN 'VERIFIED' ELSE 'FAILED' \nEND AS cost_allocation_tags,\nCASE \n    WHEN (SELECT SUM(resource_column_count) FROM resource_columns_query) > 0 THEN 'VERIFIED' ELSE 'FAILED' \nEND AS resource_id_columns"
    }
   ]
  },
  {
   "title": "Workload Cost Trends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
     "options": {
      "content": "The period over period analysis tabs will showcase cost for the selected date and time period _N_ , for N-1 period and calculate delta as a percentage.  For example if you today is Friday and you select \"Last 2 Days\" in the time period the widgets will display Friday and Thursday for the \"Selcted Time Period\".  Data for Wednesday and Tuesday for the \"Prior Time Period\" and calculate the percantage change between the two periods.  If you do not have data or tags as far bag as the prior time period, the widget will display a 0. "
     },
     "targets": [
      { "queryMode": "Metrics", "region": "$Regions", "statistic": "Average" }
     ]
    },
    {
     "title": "Compute - Period over Period Analysis",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena\n-- To view resource names add in line_item_resource_id to the SELECT and GROUP BY statements\nWITH CURRENT_PERIOD_COST AS (\nSELECT\ndate_diff(\n  '$Granularity', \n  $__timeFrom(line_item_usage_start_date),  \n  $__timeTo(line_item_usage_start_date)\n) as HOURS,\nSUM(line_item_unblended_cost) as period_one_cost\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date) \n  AND line_item_product_code = 'AmazonEC2'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type Like '%Usage%'\nGROUP BY\n1\nLIMIT 1\n)\n  \nSELECT\n(SELECT period_one_cost FROM CURRENT_PERIOD_COST) as Cost\nFROM \n$CurTable\nLIMIT 1"
      },
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena\n-- To view resource names add in line_item_resource_id to the SELECT and GROUP BY statements\n\nWITH CURRENT_PERIOD_COST AS (\nSELECT\ndate_diff(\n  'hour', \n  $__timeFrom(line_item_usage_start_date),  \n  $__timeTo(line_item_usage_start_date)\n) as HOURS,\nSUM(line_item_unblended_cost) as period_one_cost\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date) \n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type Like '%Usage%'\n  AND resource_tags_user_$TagKey IN ($TagValue)\nGROUP BY\n1\nLIMIT 1\n)\n  \nSELECT\n  SUM(line_item_unblended_cost) as Cost\nFROM \n  $CurTable\nWHERE\n  line_item_usage_start_date >= $__timeFrom(line_item_usage_start_date) - (SELECT HOURS FROM CURRENT_PERIOD_COST) * INTERVAL '1' HOUR\n  AND line_item_usage_start_date <= $__timeFrom(line_item_usage_start_date)\n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type Like '%Usage%'\n  AND resource_tags_user_$TagKey IN ($TagValue)"
      },
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena\n-- To view resource names add in line_item_resource_id to the SELECT and GROUP BY statements\nWITH CURRENT_PERIOD_COST AS (\nSELECT\ndate_diff(\n  'hour', \n  $__timeFrom(line_item_usage_start_date),  \n  $__timeTo(line_item_usage_start_date)\n) as HOURS,\nSUM(line_item_unblended_cost) as period_one_cost\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date) \n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type Like '%Usage%'\n  AND resource_tags_user_$TagKey IN ($TagValue)\nGROUP BY\n1\nLIMIT 1\n)\n  \nSELECT\n  ((SELECT period_one_cost FROM CURRENT_PERIOD_COST) - SUM(line_item_unblended_cost)) / (SUM(line_item_unblended_cost)) as Change\nFROM \n  $CurTable\nWHERE\n  line_item_usage_start_date >= $__timeFrom(line_item_usage_start_date) - (SELECT HOURS FROM CURRENT_PERIOD_COST) * INTERVAL '1' HOUR\n  AND line_item_usage_start_date <= $__timeFrom(line_item_usage_start_date)\n  AND line_item_product_code = 'AmazonEC2'\n  AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type Like '%Usage%'\n  AND resource_tags_user_$TagKey IN ($TagValue)\nLIMIT 1;\n"
      }
     ]
    },
    {
     "title": "Load Balancer - Period over Period Analysis",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena\n-- To view resource names add in line_item_resource_id to the SELECT and GROUP BY statements\nWITH CURRENT_PERIOD_COST AS (\nSELECT\ndate_diff(\n  '$Granularity', \n  $__timeFrom(line_item_usage_start_date),  \n  $__timeTo(line_item_usage_start_date)\n) as HOURS,\nSUM(line_item_unblended_cost) as period_one_cost\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date) \n  AND line_item_product_code = 'AWSELB'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND line_item_usage_type = 'LoadBalancerUsage' \n  AND line_item_operation LIKE '%LoadBalancing%'\nGROUP BY\n1\nLIMIT 1\n)\n  \nSELECT\n  (SELECT period_one_cost FROM CURRENT_PERIOD_COST) as Cost\nFROM \n  $CurTable\nLIMIT 1"
      },
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "WITH CURRENT_PERIOD_COST AS (\nSELECT\ndate_diff(\n  'hour', \n  $__timeFrom(line_item_usage_start_date),  \n  $__timeTo(line_item_usage_start_date)\n) as HOURS,\nSUM(line_item_unblended_cost) as period_one_cost\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date) \n  AND line_item_product_code = 'AWSELB'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND line_item_usage_type = 'LoadBalancerUsage' \n  AND line_item_operation LIKE '%LoadBalancing%'\nGROUP BY\n1\nLIMIT 1\n)\n  \nSELECT\n  SUM(line_item_unblended_cost) as Cost\nFROM \n  $CurTable\nWHERE\n  line_item_usage_start_date >= $__timeFrom(line_item_usage_start_date) - (SELECT HOURS FROM CURRENT_PERIOD_COST) * INTERVAL '1' HOUR\n  AND line_item_usage_start_date <= $__timeFrom(line_item_usage_start_date)\n  AND line_item_product_code = 'AWSELB'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND line_item_usage_type = 'LoadBalancerUsage' \n  AND line_item_operation LIKE '%LoadBalancing%'"
      },
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "WITH CURRENT_PERIOD_COST AS (\nSELECT\ndate_diff(\n  'hour', \n  $__timeFrom(line_item_usage_start_date),  \n  $__timeTo(line_item_usage_start_date)\n) as HOURS,\nSUM(line_item_unblended_cost) as period_one_cost\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date) \n  AND line_item_product_code = 'AWSELB'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND line_item_usage_type = 'LoadBalancerUsage' \n  AND line_item_operation LIKE '%LoadBalancing%'\nLIMIT 1\n)\n  \nSELECT\n  ((SELECT period_one_cost FROM CURRENT_PERIOD_COST) - SUM(line_item_unblended_cost)) / (SUM(line_item_unblended_cost)) as Change\nFROM \n  $CurTable\nWHERE\n  line_item_usage_start_date >= $__timeFrom(line_item_usage_start_date) - (SELECT HOURS FROM CURRENT_PERIOD_COST) * INTERVAL '1' HOUR\n  AND line_item_usage_start_date <= $__timeFrom(line_item_usage_start_date)\n  AND line_item_product_code = 'AWSELB'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND line_item_usage_type = 'LoadBalancerUsage' \n  AND line_item_operation LIKE '%LoadBalancing%'\nLIMIT 1;\n"
      }
     ]
    },
    {
     "title": "Network - Period over Period Analysis",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena\n-- To view resource names add in line_item_resource_id to the SELECT and GROUP BY statements\nWITH CURRENT_PERIOD_COST AS (\nSELECT\ndate_diff(\n  '$Granularity', \n  $__timeFrom(line_item_usage_start_date),  \n  $__timeTo(line_item_usage_start_date)\n) as HOURS,\nSUM(line_item_unblended_cost) as period_one_cost\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date) \n  AND (line_item_product_code = 'AWSELB' OR line_item_product_code = 'AmazonEC2')\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND (line_item_usage_type LIKE '%-Bytes' OR line_item_usage_type = 'LCUUsage' OR line_item_usage_type = 'NLCUUsage')\nGROUP BY\n1\nLIMIT 1\n)\n  \nSELECT\n  (SELECT period_one_cost FROM CURRENT_PERIOD_COST) as Cost\nFROM \n  $CurTable\nLIMIT 1"
      },
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena\n-- To view resource names add in line_item_resource_id to the SELECT and GROUP BY statements\nWITH CURRENT_PERIOD_COST AS (\nSELECT\ndate_diff(\n  'hour', \n  $__timeFrom(line_item_usage_start_date),  \n  $__timeTo(line_item_usage_start_date)\n) as HOURS,\nSUM(line_item_unblended_cost) as period_one_cost\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date) \n  AND (line_item_product_code = 'AWSELB' OR line_item_product_code = 'AmazonEC2')\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND (line_item_usage_type LIKE '%-Bytes' OR line_item_usage_type = 'LCUUsage' OR line_item_usage_type = 'NLCUUsage')\nGROUP BY\n1\nLIMIT 1\n)\n  \nSELECT\n  SUM(line_item_unblended_cost) as Cost\nFROM \n  $CurTable\nWHERE\n  line_item_usage_start_date >= $__timeFrom(line_item_usage_start_date) - (SELECT HOURS FROM CURRENT_PERIOD_COST) * INTERVAL '1' HOUR\n  AND line_item_usage_start_date <= $__timeFrom(line_item_usage_start_date)\n  AND (line_item_product_code = 'AWSELB' OR line_item_product_code = 'AmazonEC2')\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND (line_item_usage_type LIKE '%-Bytes' OR line_item_usage_type = 'LCUUsage' OR line_item_usage_type = 'NLCUUsage')"
      },
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena\n-- To view resource names add in line_item_resource_id to the SELECT and GROUP BY statements\nWITH CURRENT_PERIOD_COST AS (\nSELECT\ndate_diff(\n  'hour', \n  $__timeFrom(line_item_usage_start_date),  \n  $__timeTo(line_item_usage_start_date)\n) as HOURS,\nSUM(line_item_unblended_cost) as period_one_cost\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date) \n  AND (line_item_product_code = 'AWSELB' OR line_item_product_code = 'AmazonEC2')\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND (line_item_usage_type LIKE '%-Bytes' OR line_item_usage_type = 'LCUUsage' OR line_item_usage_type = 'NLCUUsage')\nLIMIT 1\n)\n  \nSELECT\n  ((SELECT period_one_cost FROM CURRENT_PERIOD_COST) - SUM(line_item_unblended_cost)) / (SUM(line_item_unblended_cost)) as Change\nFROM \n  $CurTable\nWHERE\n  line_item_usage_start_date >= $__timeFrom(line_item_usage_start_date) - (SELECT HOURS FROM CURRENT_PERIOD_COST) * INTERVAL '1' HOUR\n  AND line_item_usage_start_date <= $__timeFrom(line_item_usage_start_date)\n  AND (line_item_product_code = 'AWSELB' OR line_item_product_code = 'AmazonEC2')\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND (line_item_usage_type LIKE '%-Bytes' OR line_item_usage_type = 'LCUUsage' OR line_item_usage_type = 'NLCUUsage')\nLIMIT 1;\n"
      }
     ]
    },
    {
     "title": "NAT Gateway - Period over Period Analysis",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena\n-- To view resource names add in line_item_resource_id to the SELECT and GROUP BY statements\nWITH CURRENT_PERIOD_COST AS (\nSELECT\ndate_diff(\n  '$Granularity', \n  $__timeFrom(line_item_usage_start_date),  \n  $__timeTo(line_item_usage_start_date)\n) as HOURS,\nSUM(line_item_unblended_cost) as period_one_cost\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date) \n  AND line_item_product_code = 'AmazonEC2'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND line_item_usage_type LIKE 'NatGateway-Hours'\n  AND line_item_operation = 'NatGateway'\nGROUP BY\n1\nLIMIT 1\n)\n  \nSELECT\n  (SELECT period_one_cost FROM CURRENT_PERIOD_COST) as Cost\nFROM \n  $CurTable\nLIMIT 1"
      },
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "WITH CURRENT_PERIOD_COST AS (\nSELECT\ndate_diff(\n  'hour', \n  $__timeFrom(line_item_usage_start_date),  \n  $__timeTo(line_item_usage_start_date)\n) as HOURS,\nSUM(line_item_unblended_cost) as period_one_cost\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date) \n  AND line_item_product_code = 'AmazonEC2'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND line_item_usage_type LIKE 'NatGateway-Hours'\n  AND line_item_operation = 'NatGateway'\nGROUP BY\n1\nLIMIT 1\n)\n  \nSELECT\n  SUM(line_item_unblended_cost) as Cost\nFROM \n  $CurTable\nWHERE\n  line_item_usage_start_date >= $__timeFrom(line_item_usage_start_date) - (SELECT HOURS FROM CURRENT_PERIOD_COST) * INTERVAL '1' HOUR\n  AND line_item_usage_start_date <= $__timeFrom(line_item_usage_start_date)\n  AND line_item_product_code = 'AmazonEC2'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND line_item_usage_type LIKE 'NatGateway-Hours'\n  AND line_item_operation = 'NatGateway'"
      },
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "WITH CURRENT_PERIOD_COST AS (\nSELECT\ndate_diff(\n  'hour', \n  $__timeFrom(line_item_usage_start_date),  \n  $__timeTo(line_item_usage_start_date)\n) as HOURS,\nSUM(line_item_unblended_cost) as period_one_cost\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date) \n  AND line_item_product_code = 'AmazonEC2'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND line_item_usage_type LIKE 'NatGateway-Hours'\n  AND line_item_operation = 'NatGateway'\nLIMIT 1\n)\n  \nSELECT\n(SELECT period_one_cost FROM CURRENT_PERIOD_COST) / (SUM(line_item_unblended_cost)) - 1 as Change\nFROM \n$CurTable\nWHERE\nline_item_usage_start_date >= $__timeFrom(line_item_usage_start_date) - (SELECT HOURS FROM CURRENT_PERIOD_COST) * INTERVAL '1' HOUR\nAND line_item_usage_start_date <= $__timeFrom(line_item_usage_start_date)\nAND line_item_product_code = 'AmazonEC2'\nAND resource_tags_user_$TagKey IN ($TagValue)\nAND line_item_usage_type LIKE 'NatGateway-Hours'\nAND line_item_operation = 'NatGateway'\nLIMIT 1;\n"
      }
     ]
    },
    {
     "title": "Service Cost Trends",
     "type": "timeseries",
     "description": "Compute  Cost - Cost of compute for all instances in ASG\nLoadbalance Cost - Cost for Load Balancer and LCUUsage\nNetworking Cost - Cost for instance traffic, NAT Gateway Traffic and Load Balancer Traffic\nNatgateway Cost - Hourly Charge for NAT Gateway",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena\n-- To view resource names add in line_item_resource_id to the SELECT and GROUP BY statements\nSELECT \n  date_trunc('$Granularity', line_item_usage_start_date),\n  SUM(line_item_unblended_cost) as Cost\nFROM\n$CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date) \n  AND line_item_product_code = 'AmazonEC2'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND line_item_usage_type LIke '%Usage%'\n  AND line_item_operation = 'RunInstances'\nGROUP BY \n  1\nHAVING SUM(line_item_unblended_cost) > 0"
      },
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena\n-- To view resource names add in line_item_resource_id to the SELECT and GROUP BY statements\nSELECT \n  date_trunc('$Granularity', line_item_usage_start_date),\n  SUM(line_item_unblended_cost) as Cost\nFROM\n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date) \n  AND line_item_product_code = 'AWSELB'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND line_item_usage_type = 'LoadBalancerUsage' \n  AND line_item_operation LIKE '%LoadBalancing%'\nGROUP BY \n  1\nHAVING SUM(line_item_unblended_cost) > 0"
      },
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena\n-- To view resource names add in line_item_resource_id to the SELECT and GROUP BY statements\nSELECT \ndate_trunc('$Granularity', line_item_usage_start_date),\nSUM(line_item_unblended_cost) as Cost\nFROM\n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date) \n  AND (line_item_product_code = 'AWSELB' OR line_item_product_code = 'AmazonEC2')\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND (line_item_usage_type LIKE '%-Bytes' OR line_item_usage_type = 'LCUUsage' OR line_item_usage_type = 'NLCUUsage')\nGROUP BY \n  1\nHAVING SUM(line_item_unblended_cost) > 0"
      },
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena\n-- To view resource names add in line_item_resource_id to the SELECT and GROUP BY statements\nSELECT \n  date_trunc('$Granularity', line_item_usage_start_date),\n  SUM(line_item_unblended_cost) as Cost\nFROM\n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date) \n  AND line_item_product_code = 'AmazonEC2'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND line_item_usage_type LIKE 'NatGateway-Hours'\n  AND line_item_operation = 'NatGateway'\nGROUP BY \n  1\nHAVING SUM(line_item_unblended_cost) > 0"
      }
     ]
    },
    {
     "title": "Compute Cost by AZ - Tag: $TagKey Value: $TagValue",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena\n-- To view resource names add in line_item_resource_id to the SELECT and GROUP BY statements\nSELECT \n  line_item_availability_zone,\n  SUM(line_item_unblended_cost) as cost\nFROM\n  $CurTable\nWHERE \n$__timeFilter(line_item_usage_start_date)\nAND line_item_product_code = 'AmazonEC2'\nAND resource_tags_user_$TagKey IN ($TagValue)\nAND line_item_operation = 'RunInstances'\nAND line_item_usage_type Like '%Usage%'\nGROUP BY \n1"
      }
     ]
    },
    {
     "title": "Compute Cost by Instance - Tag: $TagKey Value: $TagValue",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena\n-- To view resource names add in line_item_resource_id to the SELECT and GROUP BY statements\nSELECT \n  product_instance_type as instance_type,\n  SUM(line_item_unblended_cost) as cost\nFROM\n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_product_code = 'AmazonEC2'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type Like '%Usage%'\nGROUP BY \n1"
      }
     ]
    }
   ]
  },
  {
   "title": "Compute - Autoscaling Group: $ASGName",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scaling Activity - ASG: $ASGName",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena \nSELECT\n  date_trunc('$Granularity', line_item_usage_start_date),\n  SUM(line_item_unblended_cost) as Cost\nFROM $CurTable\nWHERE\n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_product_code = 'AmazonEC2'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type Like '%Usage%'\n  AND product_region = '$Regions' \n  --AND line_item_usage_account_id IN ($LinkedAccounts) --future use\n  --AND $CurTable .line_item_product_code in ($Services) --future use\nGROUP BY 1"
      },
      {
       "expression": "SEARCH('{AWS/AutoScaling,AutoScalingGroupName} MetricName=\"GroupTotalInstances\" \"$ASGName\"', 'Average', 300)",
       "metricEditorMode": 1,
       "queryMode": "Metrics",
       "region": "$Regions",
       "statistic": "Average"
      },
      {
       "expression": "SEARCH('{AWS/AutoScaling,AutoScalingGroupName} MetricName=\"GroupDesiredCapacity\" \"$ASGName\"', 'Average', 300)",
       "metricEditorMode": 1,
       "queryMode": "Metrics",
       "region": "$Regions",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Average CPU - ASG: $ASGName",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena \nSELECT\n  date_trunc('$Granularity', line_item_usage_start_date),\n  SUM(line_item_unblended_cost) as cost\nfrom $CurTable\nWHERE\n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_product_code = 'AmazonEC2'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type Like '%Usage%'\n  AND product_region = '$Regions'\n  --AND line_item_usage_account_id IN ($LinkedAccounts) --future use\n  --AND $CurTable .line_item_product_code in ($Services) -- future use\nGROUP BY 1\nORDER BY 1"
      },
      {
       "expression": "REMOVE_EMPTY(SEARCH('{\"AWS/EC2\",\"AutoScalingGroupName\"} MetricName=\"CPUUtilization\" \"$ASGName\"', 'Average', 300))",
       "metricEditorMode": 1,
       "queryMode": "Metrics",
       "region": "$Regions",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Instance Status Check Failed - ASG: $ASGName",
     "type": "timeseries",
     "description": "Status failure Metrics for the entire ASG. This metric reports whether the instance has passed both the instance status check and the system status check in the last minute. This metric can be either 0 (passed) or 1 (failed). By default, this metric is available at a 1-minute frequency at no charge.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena\n-- To view resource names add in line_item_resource_id to the SELECT and GROUP BY statements\nSELECT\n  date_trunc('$Granularity', line_item_usage_start_date),\n  SUM(line_item_unblended_cost) as cost\nfrom $CurTable\nWHERE\n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_product_code = 'AmazonEC2'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type Like '%Usage%'\n  AND product_region = '$Regions' \n  --AND line_item_usage_account_id IN ($LinkedAccounts)\n  --AND $CurTable .line_item_product_code in ($Services)\nGROUP BY 1\nORDER BY 1"
      },
      {
       "expression": "SEARCH('{\"AWS/EC2\",\"AutoScalingGroupName\"} MetricName=\"StatusCheckFailed\" \"$ASGName\"', 'Average', 300)",
       "metricEditorMode": 1,
       "queryMode": "Metrics",
       "region": "$Regions",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "CPU Credit Balance - ASG: $ASGName",
     "type": "timeseries",
     "description": "The number of earned CPU credits (T instances) that an instance(s) have accrued since they were launched or started for the named Auto Scaling Group. Credits are accrued in the credit balance after they are earned, and removed from the credit balance when they are spent. The credit balance has a maximum limit, determined by the instance size. ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena\n-- To view resource names add in line_item_resource_id to the SELECT and GROUP BY statements\nSELECT\n  date_trunc('$Granularity', line_item_usage_start_date),\n  SUM(line_item_unblended_cost) as cost\nfrom $CurTable\nWHERE\n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_product_code = 'AmazonEC2'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type Like '%Usage%'\n  AND product_region = '$Regions' \n  --AND line_item_usage_account_id IN ($LinkedAccounts) -- future use\n  --AND $CurTable .line_item_product_code in ($Services) -- future use\nGROUP BY 1\nORDER BY 1"
      },
      {
       "expression": "SEARCH('{\"AWS/EC2\",\"AutoScalingGroupName\"} MetricName=\"CPUCreditUsage\" \"$ASGName\"', 'Average', 300)",
       "metricEditorMode": 1,
       "queryMode": "Metrics",
       "region": "$Regions",
       "statistic": "Average"
      },
      {
       "expression": "SEARCH('{\"AWS/EC2\",\"AutoScalingGroupName\"} MetricName=\"CPUCreditBalance\" \"$ASGName\"', 'Average', 300)",
       "metricEditorMode": 1,
       "queryMode": "Metrics",
       "region": "$Regions",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Network - Autoscaling Group: $ASGName",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "EC2 Networking Bytes Out- ASG: $ASGName",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena\n-- To view resource names add in line_item_resource_id to the SELECT and GROUP BY statements\nSELECT \n  date_trunc('$Granularity', line_item_usage_start_date),\n  SUM(line_item_unblended_cost) as cost\nFROM\n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_product_code = 'AmazonEC2'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  -- AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type LIKE '%AWS%Bytes%'\n  AND product_region = '$Regions' \nGROUP BY \n1\nHAVING SUM(line_item_unblended_cost) > 0\n\n"
      },
      {
       "expression": "SEARCH('{\"AWS/EC2\",\"AutoScalingGroupName\"} MetricName=\"NetworkOut\" \"$ASGName\"', 'Average', 300)",
       "metricEditorMode": 1,
       "queryMode": "Metrics",
       "region": "$Regions",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "EC2 Networking Packets Out - ASG: $ASGName",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena\n-- To view resource names add in line_item_resource_id to the SELECT and GROUP BY statements\nSELECT \n  date_trunc('$Granularity', line_item_usage_start_date),\n  SUM(line_item_unblended_cost) as cost\nFROM\n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_product_code = 'AmazonEC2'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  -- AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type LIKE '%AWS%Bytes%'\n  AND product_region = '$Regions' \nGROUP BY \n1\nHAVING SUM(line_item_unblended_cost) > 0\n\n"
      },
      {
       "expression": "SEARCH('{\"AWS/EC2\",\"AutoScalingGroupName\"} MetricName=\"NetworkPacketsOut\" \"$ASGName\"', 'Average', 300)",
       "metricEditorMode": 1,
       "queryMode": "Metrics",
       "region": "$Regions",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "EBS Activity - $ASGName",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "EBS Volume Read/Write- ASG: $ASGName",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena\n-- To view resource names add in line_item_resource_id to the SELECT and GROUP BY statements\nSELECT \n  date_trunc('$Granularity', line_item_usage_start_date),\n  SUM(line_item_unblended_cost) as cost\nFROM\n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_product_code = 'AmazonEC2'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND line_item_usage_type Like '%VolumeUsage%'\n  AND product_region = '$Regions' \nGROUP BY \n1\nHAVING SUM(line_item_unblended_cost) > 0"
      },
      {
       "expression": "SEARCH('{\"AWS/EC2\",\"AutoScalingGroupName\"} MetricName=\"EBSReadBytes\" \"$ASGName\"', 'Average', 300)",
       "metricEditorMode": 1,
       "queryMode": "Metrics",
       "region": "$Regions",
       "statistic": "Average"
      },
      {
       "expression": "SEARCH('{\"AWS/EC2\",\"AutoScalingGroupName\"} MetricName=\"EBSWriteBytes\" \"$ASGName\"', 'Average', 300)",
       "metricEditorMode": 1,
       "queryMode": "Metrics",
       "region": "$Regions",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "EBS Volume Read/Write IOPS ASG: $ASGName",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena\n-- To view resource names add in line_item_resource_id to the SELECT and GROUP BY statements\nSELECT \n  date_trunc('$Granularity', line_item_usage_start_date),\n  SUM(line_item_unblended_cost) as cost\nFROM\n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_product_code = 'AmazonEC2'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND line_item_usage_type Like '%VolumeUsage%'\n  AND product_region = '$Regions' \nGROUP BY \n1\nHAVING SUM(line_item_unblended_cost) > 0"
      },
      {
       "expression": "SEARCH('{\"AWS/EC2\",\"AutoScalingGroupName\"} MetricName=\"EBSReadOps\" \"$ASGName\"', 'Average', 300)",
       "metricEditorMode": 1,
       "queryMode": "Metrics",
       "region": "$Regions",
       "statistic": "Average"
      },
      {
       "expression": "SEARCH('{\"AWS/EC2\",\"AutoScalingGroupName\"} MetricName=\"EBSWriteOps\" \"$ASGName\"', 'Average', 300)",
       "metricEditorMode": 1,
       "queryMode": "Metrics",
       "region": "$Regions",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "ELB Networking - TagValue: $TagValue - LBName: $LBName",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "LBName",
   "collapsed": true,
   "panels": [
    {
     "title": "LCU Metrics  - ELB: $LBName",
     "type": "timeseries",
     "description": "Load Balancer LCU Usage for $LBName - Be sure to update the Load Balancer Name variable at the top of the dashboard.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena\n-- To view resource names add in line_item_resource_id to the SELECT and GROUP BY statements\nSELECT\ndate_trunc('$Granularity', line_item_usage_start_date),\nSUM(line_item_unblended_cost) as cost\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date) \n  AND line_item_product_code = 'AWSELB'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND (line_item_usage_type LIKE '%LCUUsage' OR line_item_usage_type LIKE '%NLCUUsage')\n  AND line_item_operation LIKE '%LoadBalancing%'\n  AND line_item_resource_id LIKE CONCAT('%', '$LBName')\n  AND product_region = '$Regions' \n  GROUP BY\n  1\n  HAVING SUM(line_item_unblended_cost) > 0 \n"
      },
      {
       "expression": "SEARCH('{\"AWS/ApplicationELB\",\"LoadBalancer\"} MetricName=\"ConsumedLCUs\" \"$LBName\"', 'Average', 300)",
       "metricEditorMode": 1,
       "queryMode": "Metrics",
       "region": "$Regions",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Hourly Cost and Requests  - ELB: $LBName",
     "type": "timeseries",
     "description": "Load Balancer LCU Usage for ELB $LBName - Be sure to update the Load Balancer Name variable at the top of the dashboard.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena\n-- To view resource names add in line_item_resource_id to the SELECT and GROUP BY statements\nSELECT\ndate_trunc('$Granularity', line_item_usage_start_date),\nSUM(line_item_unblended_cost) as cost\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date) \n  AND line_item_product_code = 'AWSELB'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND line_item_usage_type LIKE '%LoadBalancerUsage' \n  AND line_item_operation LIKE '%LoadBalancing%'\n  AND line_item_resource_id LIKE CONCAT('%', '$LBName')\n  AND product_region = '$Regions' \n  GROUP BY\n  1\n  HAVING SUM(line_item_unblended_cost) > 0 \n"
      },
      {
       "expression": "SEARCH('{\"AWS/ApplicationELB\",\"LoadBalancer\"} MetricName=\"ConsumedLCUs\" \"$LBName\"', 'Average', 300)",
       "metricEditorMode": 1,
       "queryMode": "Metrics",
       "region": "$Regions",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "NatGateway - TagValue: $TagValue - NGWName - $NGWName",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "NGWName",
   "collapsed": true,
   "panels": [
    {
     "title": "NatGateway Traffic Cost",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena\n-- To view resource names add in line_item_resource_id to the SELECT and GROUP BY statements\nSELECT\ndate_trunc('$Granularity', line_item_usage_start_date),\nSUM(line_item_unblended_cost) as cost\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date) \n  AND line_item_product_code = 'AmazonEC2'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND line_item_usage_type = 'NatGateway-Bytes'\n  AND line_item_operation = 'NatGateway'\n  AND line_item_resource_id LIKE CONCAT('%', '$NGWName')\n  AND product_region = '$Regions' \n  GROUP BY\n  1\n"
      },
      {
       "expression": "SEARCH('{\"AWS/NATGateway\",\"NatGatewayId\"} MetricName=\"BytesOutToDestination\" \"$NGWName\"', 'Average', 300)",
       "metricEditorMode": 1,
       "queryMode": "Metrics",
       "region": "$Regions",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "NatGateway Test",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "connectionArgs": {
        "catalog": "__default",
        "database": "__default",
        "region": "__default",
        "resultReuseEnabled": false,
        "resultReuseMaxAgeInMinutes": 60
       },
       "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena\n-- To view resource names add in line_item_resource_id to the SELECT and GROUP BY statements\nSELECT\ndate_trunc('$Granularity', line_item_usage_start_date),\nSUM(line_item_unblended_cost) as cost\nFROM \n  $CurTable\nWHERE \n  $__timeFilter(line_item_usage_start_date) \n  AND line_item_product_code = 'AmazonEC2'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND line_item_usage_type = 'NatGateway-Hours'\n  AND line_item_operation = 'NatGateway'\n  AND line_item_resource_id LIKE CONCAT('%', '$NGWName')\n  AND product_region = '$Regions' \n  GROUP BY\n  1\n"
      },
      {
       "expression": "SEARCH('{\"AWS/NATGateway\",\"NatGatewayId\"} MetricName=\"BytesOutToDestination\" \"$NGWName\"', 'Average', 300)",
       "metricEditorMode": 1,
       "queryMode": "Metrics",
       "region": "$Regions",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  { "title": "Resource Index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Compute Resources (EC2)",
   "type": "table",
   "description": "Compute resources with tag_key: $TagKey and tag_value: $TagValue observed in the past 30 days.  The last_observed column will list the timestamp when the resource was last seen in the CUR file.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "-- When troubleshooting a query, it helps to use the Query Inspector button and copy the query into Athena \nSELECT\n  line_item_resource_id as instance_id,\n  product_instance_type as instance_type,\n  product_vcpu as vcpu,\n  product_physical_processor,\n  MAX(line_item_usage_start_date) AS last_observed\nFROM $CurTable\nWHERE\n  -- $__timeFilter(line_item_usage_start_date)\n  line_item_product_code = 'AmazonEC2'\n  AND resource_tags_user_$TagKey IN ($TagValue)\n  AND line_item_operation = 'RunInstances'\n  AND line_item_usage_type Like '%Usage%'\n  AND product_region = '$Regions'\n  --AND line_item_usage_account_id IN ($LinkedAccounts) --future use\n  --AND $CurTable .line_item_product_code in ($Services) -- future use\n  AND line_item_usage_start_date <= CURRENT_DATE\n  AND line_item_usage_start_date >= DATE_ADD('day', -30, CURRENT_DATE)\nGROUP BY 1,2,3,4\nORDER BY 5 DESC"
    }
   ]
  },
  {
   "title": "Annotations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Annotations",
     "type": "annolist",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "targets": [
      { "queryMode": "Metrics", "region": "$Regions", "statistic": "Average" }
     ]
    }
   ]
  }
 ]
}