{
 "title": "COAST Cost",
 "description": "Advanced Cost and Usage Analysis Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "grafana-athena-datasource" },
   {
    "name": "CurTable",
    "label": "CUR Table",
    "query": {}
   },
   {
    "name": "LinkedAccounts",
    "label": "Linked Accounts",
    "query": {}
   },
   {
    "name": "Regions",
    "label": "Regions",
    "query": {}
   },
   {
    "name": "Services",
    "label": "Services",
    "query": {}
   },
   { "name": "Granularity", "label": "Granularity", "query": "month,day,hour" },
   {
    "name": "ChargeType",
    "label": "Charge Type",
    "query": {}
   },
   {
    "name": "TagKey",
    "label": "Tag Key",
    "query": {}
   },
   {
    "name": "TagValue",
    "label": "Tag Value",
    "query": {}
   },
   {
    "name": "CostCategoryName",
    "label": "Cost Category Name",
    "query": {}
   },
   {
    "name": "CostCategoryValue",
    "label": "Cost Category Value",
    "query": {}
   },
   {
    "name": "PanelTop25SpendPercentage",
    "query": {}
   },
   {
    "name": "TotalAccountInOrganization",
    "query": {}
   },
   {
    "name": "GrafanaWorkspace",
    "label": "Grafana Workspace",
    "query": {}
   },
   { "name": "CfnStackName", "label": "CloudFormation Stack Name", "query": "coast-raiders" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Directions\n\nEnter Select the appropriate workspace and enter the name of the CloudFormation stack which deployed COAST\n"
   }
  },
  {
   "title": "COAST Cost: Previous Month",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "with glue_cost_query as (\nSELECT\nCOUNT(*) as glue_count,\nSUM(line_item_unblended_cost) as glue_cost\nFROM csaws_cur\nWHERE\nline_item_product_code = 'AWSGlue'\nAND line_item_operation = 'CrawlerRun'\nAND line_item_resource_id LIKE '%$CfnStackName%'\nAND (line_item_usage_start_date >= date_add('month', -1, date_trunc('month', current_timestamp)) \n     AND line_item_usage_start_date < date_add('month', -0, date_trunc('month', current_timestamp)) )\n),\n\nathena_cost_query as (\nSELECT\nCOUNT(*) as athena_count,\nSUM(line_item_unblended_cost) as athena_cost\nFROM csaws_cur\nWHERE\nline_item_product_code = 'AmazonAthena'\nAND line_item_resource_id LIKE '%$CfnStackName%'\nAND (line_item_usage_start_date >= date_add('month', -1, date_trunc('month', current_timestamp)) \n     AND line_item_usage_start_date < date_add('month', -0, date_trunc('month', current_timestamp)) )\n),\n\ngrafana_cost_query as (\nSELECT\nCOUNT(*) as grafana_count,\nSUM(line_item_unblended_cost) as grafana_cost\nFROM csaws_cur\nWHERE\nline_item_product_code = 'AmazonGrafana'\nAND line_item_operation LIKE '$GrafanaWorkspace'\nAND (line_item_usage_start_date >= date_add('month', -1, date_trunc('month', current_timestamp)) \n     AND line_item_usage_start_date < date_add('month', -0, date_trunc('month', current_timestamp)) )\n)\n\nSELECT\n(CASE\nWHEN (SELECT glue_count from glue_cost_query) > 0 THEN (SELECT glue_cost from glue_cost_query)\nELSE 0\nEND + \nCASE WHEN (SELECT athena_count from athena_cost_query) > 0 THEN (SELECT athena_cost from athena_cost_query)\nELSE 0\nEND + \nCASE WHEN (SELECT grafana_count from grafana_cost_query) > 0 THEN (SELECT grafana_cost from grafana_cost_query)\nELSE 0\nEND) as cost"
    }
   ]
  },
  {
   "title": "COAST Cost: Current Month",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "with glue_cost_query as (\nSELECT\nCOUNT(*) as glue_count,\nSUM(line_item_unblended_cost) as glue_cost\nFROM csaws_cur\nWHERE\nline_item_product_code = 'AWSGlue'\nAND line_item_operation = 'CrawlerRun'\nAND line_item_resource_id LIKE '%$CfnStackName%'\nAND date_trunc('month', line_item_usage_start_date) = date_trunc('month', current_timestamp)\n),\n\nathena_cost_query as (\nSELECT\nCOUNT(*) as athena_count,\nSUM(line_item_unblended_cost) as athena_cost\nFROM csaws_cur\nWHERE\nline_item_product_code = 'AmazonAthena'\nAND line_item_resource_id LIKE '%$CfnStackName%'\nAND date_trunc('month', line_item_usage_start_date) = date_trunc('month', current_timestamp)\n),\n\ngrafana_cost_query as (\nSELECT\nCOUNT(*) as grafana_count,\nSUM(line_item_unblended_cost) as grafana_cost\nFROM csaws_cur\nWHERE\nline_item_product_code = 'AmazonGrafana'\nAND line_item_operation LIKE '$GrafanaWorkspace'\nAND date_trunc('month', line_item_usage_start_date) = date_trunc('month', current_timestamp)\n)\n\nSELECT\n(CASE\nWHEN (SELECT glue_count from glue_cost_query) > 0 THEN (SELECT glue_cost from glue_cost_query)\nELSE 0\nEND + \nCASE WHEN (SELECT athena_count from athena_cost_query) > 0 THEN (SELECT athena_cost from athena_cost_query)\nELSE 0\nEND + \nCASE WHEN (SELECT grafana_count from grafana_cost_query) > 0 THEN (SELECT grafana_cost from grafana_cost_query)\nELSE 0\nEND) as cost"
    }
   ]
  },
  {
   "title": "Grafana Workspace Monthly Cost: $GrafanaWorkspace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "select \ndate_trunc('month', line_item_usage_start_date) as date,\n-- line_item_usage_type,\nSUM(line_item_unblended_cost) as cost\nFROM $CurTable\nwhere \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_product_code = 'AmazonGrafana'\n  AND line_item_operation = '$GrafanaWorkspace'\nGROUP BY \ndate_trunc('month', line_item_usage_start_date)\n-- line_item_usage_type"
    }
   ]
  },
  {
   "title": "Lamba Innovcations over cost for coast-cur-initializer-$CfnStackNam",
   "type": "timeseries",
   "description": "Athena Workgroup cost for CFN stack name: $CfnStackName",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "select \n--line_item_usage_start_date,\ndate_trunc('day', line_item_usage_start_date) as date,\nSUM(line_item_unblended_cost) as cost\nFROM $CurTable\nwhere \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_product_code = 'AWSLambda'\n  AND line_item_resource_id LIKE CONCAT('%', '$CfnStackName%')\nGROUP BY \ndate_trunc('day', line_item_usage_start_date)"
    },
    {
     "expression": "SEARCH('{\"AWS/Lambda\",\"FunctionName\"} MetricName=\"Invocations\" \"coast-cur-initializer-$CfnStackName\"', 'Average', 300)",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Lamba Duration over cost for coast-cur-initializer-$CfnStackNam",
   "type": "timeseries",
   "description": "Athena Workgroup cost for CFN stack name: $CfnStackName",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "select \n--line_item_usage_start_date,\ndate_trunc('day', line_item_usage_start_date) as date,\nSUM(line_item_unblended_cost) as cost\nFROM $CurTable\nwhere \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_product_code = 'AWSLambda'\n  AND line_item_resource_id LIKE CONCAT('%', '$CfnStackName%')\nGROUP BY \ndate_trunc('day', line_item_usage_start_date)"
    },
    {
     "expression": "SEARCH('{\"AWS/Lambda\",\"FunctionName\"} MetricName=\"Duration\" \"coast-cur-initializer-$CfnStackName\"', 'Average', 300)",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Glue Crawler Jobs ",
   "type": "timeseries",
   "description": "Glue Crawler Jobs Executions From Cloudwatch logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "select \n--line_item_usage_start_date,\ndate_trunc('day', line_item_usage_start_date) as date,\nCOUNT(*) as cnt\nFROM $CurTable\nwhere \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_product_code LIKE '%AWSGlue%'\n  AND line_item_resource_id LIKE CONCAT('%', 'coast-raiders%')\n  AND line_item_operation = 'CrawlerRun'\nGROUP BY 1"
    },
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "select \ndate_trunc('day', line_item_usage_start_date) as date,\nSUM(line_item_unblended_cost) as cost\nFROM $CurTable\nwhere \n  $__timeFilter(line_item_usage_start_date) \n  AND line_item_product_code = 'AWSGlue'\n  AND line_item_operation = 'CrawlerRun'\n  AND line_item_resource_id LIKE CONCAT('%', '$CfnStackName%')\nGROUP BY \ndate_trunc('day', line_item_usage_start_date)\n"
    }
   ]
  },
  {
   "title": "Athena Processed Bytes Over Cost",
   "type": "timeseries",
   "description": "Athena Workgroup cost for CFN stack name: $CfnStackName",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "select \n--line_item_usage_start_date,\ndate_trunc('day', line_item_usage_start_date) as date,\nSUM(line_item_unblended_cost) as cost\nFROM $CurTable\nwhere \n  $__timeFilter(line_item_usage_start_date)\n  AND line_item_product_code = 'AmazonAthena'\n  AND line_item_resource_id LIKE CONCAT('%', '$CfnStackName%')\nGROUP BY \ndate_trunc('day', line_item_usage_start_date)\n-- date_format(date_trunc('month', line_item_usage_start_date), '%m-%Y')\n-- line_item_usage_type"
    },
    {
     "expression": "SEARCH('{\"AWS/Athena\",\"WorkGroup\"} MetricName=\"ProcessedBytes\" \"coast-workgroup-$CfnStackName\"', 'Average', 300)",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } }
 ]
}